import type { DetectedHarness, Harness } from './types.ts';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { listFiles, listMarkdown, readText } from './fsx.ts';
import { parseFrontmatter, stripHeader, SKILL_FIELDS } from './document.ts';
import { DaorisError } from './errors.ts';

/**
 * How a given agent harness expects doctrine to be laid out on disk.
 *
 * The canon speaks one vocabulary — a document is a **rule** (always loaded), **knowledge** (read on
 * demand) or a **skill** (invoked by name) — and that vocabulary is about the *doctrine*, not about
 * any tool. A harness descriptor is the translation: where each tier lands, what a skill's entry file
 * is called, which frontmatter fields it must carry, where the generated index goes.
 *
 * Everything in here was previously a constant scattered across six modules, each quietly asserting
 * one harness's conventions as though they were universal. Naming them in one place is what makes a
 * second harness an addition rather than an excavation.
 *
 * **One implementation ships** (D23). The others are detected and reported so the gap is loud: a tree
 * installed for the wrong harness is present, correct, and never loaded — a failure with nothing to
 * notice. Writing a second descriptor is deliberately deferred until a repository actually wants it,
 * because the layout, the always-loaded semantics and the trigger mechanism all differ, and guessing
 * produces doctrine nobody chose in a format nobody verified.
 */
export const HARNESSES: Record<string, Harness> = {
  'claude-code': {
    id: 'claude-code',
    name: 'Claude Code',
    supported: true,

    /** Files whose presence says a repository is set up for this harness. */
    detect: ['.claude', 'CLAUDE.md'],

    /** Where doctrine lives, when the manifest does not say otherwise. */
    defaultTarget: '.claude',

    /**
     * 🔴 **The tier is the LOCATION** (D7 as amended by D59). The on-demand tiers are directories
     * this harness reaches for by path. The always-loaded one is a **region in `AGENTS.md`**, because
     * `.claude/rules/` is read by exactly one of the three harnesses this family drives — measured,
     * `docs/2026-09-21-dsh-evaluation.md` §6.5 — and `AGENTS.md` is the only file all three read.
     *
     * `alwaysLoaded` is still what the byte budget measures; a region has a byte count exactly as a
     * directory did, which is the half of D7 that survives.
     */
    tiers: {
      rules: { region: { file: 'AGENTS.md', name: 'rules' }, alwaysLoaded: true },
      knowledge: { dir: 'knowledge', alwaysLoaded: false },
      skills: {
        dir: 'skills',
        alwaysLoaded: false,
        // A skill is a directory whose entry point is this file; the rest are supporting material.
        entryFile: 'SKILL.md',
        // What the harness itself requires. `description` is the trigger it matches on.
        frontmatter: SKILL_FIELDS,
      },
    },

    /**
     * This harness reads `CLAUDE.md` and not `AGENTS.md`, and it follows `@path` imports — which the
     * other two do not (measured; §6.5). So one line here is what carries the tier to it, and every
     * other reader ignores that line. The roster is no longer a file of its own: it is the first
     * thing in the region, where it is loaded rather than merely present.
     */
    pointer: { file: 'CLAUDE.md', imports: 'AGENTS.md' },

    /**
     * Frontmatter must start at byte 0 or this harness does not see it, so the provenance line goes
     * beneath the closing fence rather than above the opening one (D14).
     */
    headerPlacement: 'below-frontmatter',
  },
};

/** Harnesses Daoris knows the signals for but does not generate a layout for. */
const UNSUPPORTED_SIGNALS = [
  { id: 'agents-md', name: 'the AGENTS.md convention', detect: ['AGENTS.md'] },
  { id: 'cursor', name: 'Cursor', detect: ['.cursor', '.cursorrules'] },
  { id: 'gemini-cli', name: 'Gemini CLI', detect: ['GEMINI.md', '.gemini'] },
  { id: 'copilot', name: 'GitHub Copilot', detect: ['.github/copilot-instructions.md'] },
  { id: 'aider', name: 'Aider', detect: ['.aider.conf.yml', 'CONVENTIONS.md'] },
];

export const DEFAULT_HARNESS = 'claude-code';

/**
 * The descriptor a manifest asks for.
 *
 * An unknown name is a tool error naming what exists, rather than a silent fallback to the default:
 * a repository that asked for a harness and got another one is exactly the silent-wrong-layout
 * failure this whole seam exists to prevent.
 */
export function resolveHarness(id: string = DEFAULT_HARNESS): Harness {
  const harness = HARNESSES[id];
  if (harness) return harness;

  const known = Object.keys(HARNESSES).join(', ');
  const detected = UNSUPPORTED_SIGNALS.find((s) => s.id === id);
  throw new DaorisError(
    detected
      ? `harness '${id}' (${detected.name}) is recognised but not generated by daoris yet.\n` +
        `  Supported: ${known}. Adding one is a descriptor in src/harness.ts — see docs/DECISIONS.md D23.`
      : `unknown harness '${id}' — available: ${known}`,
  );
}

/** The tier names, in the order everything iterates them. */
export const tierNames = (harness: Harness): string[] => Object.keys(harness.tiers);

/** Tiers whose bytes are loaded on every session — what the budget measures. */
export const alwaysLoadedTiers = (harness: Harness): string[] =>
  Object.entries(harness.tiers).filter(([, tier]) => tier.alwaysLoaded).map(([name]) => name);

/** Every harness this repository shows a sign of, with the evidence that said so. */
export function detectHarnesses(root: string): DetectedHarness[] {
  const found: DetectedHarness[] = [];
  for (const harness of Object.values(HARNESSES)) {
    const evidence = harness.detect.filter((path) => existsSync(join(root, path)));
    if (evidence.length) {
      found.push({ id: harness.id, name: harness.name, supported: true, evidence });
    }
  }
  for (const signal of UNSUPPORTED_SIGNALS) {
    const evidence = signal.detect.filter((path) => existsSync(join(root, path)));
    if (evidence.length) {
      found.push({ id: signal.id, name: signal.name, supported: false, evidence });
    }
  }
  return found;
}

/**
 * What a materialized tree must satisfy for this harness, checked rather than assumed.
 *
 * Only things that fail **silently** are checked here: a skill whose frontmatter cannot be parsed is
 * not an error anywhere, it simply never fires. Anything that would fail loudly is its own report.
 */
export function verifyHarnessContract(
  root: string,
  target: string,
  harness: Harness = HARNESSES[DEFAULT_HARNESS]!,
): string[] {
  const problems = [];
  const skills = harness.tiers.skills;

  if (skills?.dir) {
    const dir = join(root, target, skills.dir);
    const suffix = `/${skills.entryFile}`;
    for (const file of listFiles(dir)) {
      if (!file.endsWith(suffix)) {
        if (file.endsWith('.md') && !file.includes('/')) {
          problems.push(
            `${skills.dir}/${file} is not inside a skill directory, so it can never be invoked`,
          );
        }
        continue;
      }

      const text = readText(join(dir, file));
      if (!text.startsWith('---\n')) {
        problems.push(`${skills.dir}/${file} does not begin with frontmatter, so the harness will not surface it`);
        continue;
      }
      const { meta } = parseFrontmatter(stripHeader(text), skills.frontmatter ?? []);
      if (!meta) {
        const fields = (skills.frontmatter ?? []).map((f) => `'${f}'`).join(' or ');
        problems.push(`${skills.dir}/${file} is missing ${fields} — it installs but never fires`);
      }
    }
  }

  // A tier that IS a directory is read one level deep, so a document nested below that is never
  // read. The always-loaded tier is a span (D59) and has no directory to nest anything in.
  for (const [name, tier] of Object.entries(harness.tiers)) {
    if (tier.entryFile || !tier.dir) continue; // skills are directories on purpose; a region is not one
    const dir = join(root, target, tier.dir);
    if (!existsSync(dir)) continue;
    for (const file of listMarkdown(dir)) {
      if (file.includes('/')) {
        problems.push(`${name}/${file} is nested, and only the top level of ${tier.dir}/ is read`);
      }
    }
  }

  return problems;
}

/** A one-line verdict for a report: which harness this looks like, and whether that is supported. */
export function harnessVerdict(
  root: string,
): { detected: DetectedHarness[]; supported: DetectedHarness[]; others: DetectedHarness[] } {
  const detected = detectHarnesses(root);
  return {
    detected,
    supported: detected.filter((h) => h.supported),
    others: detected.filter((h) => !h.supported),
  };
}
