// What goes inside the region: the always-loaded tier, rendered once (CANON8b, D59).
//
// `.claude/rules/` was read by exactly one of three harnesses, so the tier moves into the file all
// three read. Eight files become one span, and three content decisions follow from that — each a
// consequence of concatenating rather than a preference:
//
//   1. FRONTMATTER IS STRIPPED. D14 already says frontmatter is only frontmatter at byte 0. Eight
//      rules concatenated would put seven `---` blocks mid-document, where a reader sees horizontal
//      rules and stray key-value prose. What it carried becomes the table.
//   2. PROVENANCE STAYS, per rule. It is what keeps drift and `upstream` per RULE inside one region,
//      which design §4 rests on — without it a person improving one sentence has drifted all eight.
//   3. THE TABLE KEEPS EVERY TIER. Knowledge and skills are not loaded, so the table is the only way
//      an agent learns they exist; the rules rows are cheap and carry the `applies_when`/`enforces`
//      the stripped frontmatter held.

import type { CanonFile } from './types.ts';
import { makeHeader, parseFrontmatter, SKILL_FIELDS } from './document.ts';

/** One canon document on its way into the region: where it came from, and what it says. */
export interface TierDocument {
  file: CanonFile;
  text: string;
}

export interface TierInput {
  rules: TierDocument[];
  knowledge: TierDocument[];
  skills: TierDocument[];
  version: string;
  /** Where the on-demand tiers live, for the rows that point at them. */
  target?: string;
}

const RULE_HEAD = '| Rule | Applies when | Enforces |\n|---|---|---|';
const KNOWLEDGE_HEAD = '| Knowledge | Applies when | Enforces |\n|---|---|---|';
const SKILL_HEAD = '| Skill | Use when |\n|---|---|';

/** A document's name — the filename, which is what every rule's frontmatter `name` must match. */
function nameOf(file: CanonFile): string {
  return file.target.replace(/^.*\//, '').replace(/\.md$/, '');
}

/** The body a document contributes: its own text, with the frontmatter gone and the edges trimmed. */
function bodyOf(text: string): string {
  const { meta, body } = parseFrontmatter(text, []);
  return (meta ? body : text).trim();
}

function metaOf(document: TierDocument, required: readonly string[] = ['applies_when', 'enforces']) {
  return parseFrontmatter(document.text, required).meta;
}

/**
 * The first sentence, capped — a skill's `description` is the harness's TRIGGER text and is long by
 * design, so copying it whole pays for it twice. The reasoning and the measurement are in
 * `indexgen.ts`, where this roster lived before the tier moved.
 */
function summarize(description: string, limit = 110): string {
  const text = description.trim();
  if (text.length <= limit) return text;
  const cut = text.lastIndexOf(' ', limit);
  return `${text.slice(0, cut > 40 ? cut : limit).trimEnd()}…`;
}

/**
 * The region's body: the roster, then every always-loaded rule in full.
 *
 * Deterministic in its input's order — the canon's own — because a region that renders differently
 * from the same canon makes every `sync` a diff and every drift report a lie.
 */
export function renderTier(input: TierInput): string {
  const target = input.target ?? '.claude';
  // 🔴 The region's own headings sit at the SAME level the rule bodies use, and the bodies are not
  // touched. Nesting them under a `## Doctrine` wrapper reads better in a table of contents and
  // requires demoting every `#` inside eight rules — a transformation that has to be exactly
  // reversible over arbitrary markdown, including inside fenced blocks, or a rule is silently
  // corrupted on its way back out through `upstream`. A body rewritten on the way in cannot be
  // compared on the way out, so the document is flat: a concatenation of documents, which is what it
  // is. Seen by rendering the real canon and reading it.
  const lines: string[] = [
    '# Doctrine',
    '',
    'Generated by daoris from the shared canon. Edit the canon, not this — a local edit here is'
    + ' reported as drift, and `daoris upstream <file>` promotes one.',
    '',
    '## Always loaded — every rule below, in full',
    '',
    RULE_HEAD,
  ];

  for (const document of input.rules) {
    const meta = metaOf(document);
    // Named, not linked. The rule is a few lines down in the same document, and a link would have to
    // guess the anchor its heading produces — which is the canon's sentence, not its filename.
    lines.push(meta
      ? `| \`${nameOf(document.file)}\` | ${meta.applies_when} | ${meta.enforces} |`
      : `| \`${nameOf(document.file)}\` | ⚠ needs frontmatter | ⚠ needs frontmatter |`);
  }

  lines.push('', '## Read on demand', '', KNOWLEDGE_HEAD);
  for (const document of input.knowledge) {
    const meta = metaOf(document);
    // Linked, because these point at real files the reader has to go and open.
    const link = `[${nameOf(document.file)}](${target}/${document.file.target})`;
    lines.push(meta
      ? `| ${link} | ${meta.applies_when} | ${meta.enforces} |`
      : `| ${link} | ⚠ needs frontmatter | ⚠ needs frontmatter |`);
  }

  lines.push('', '## Invoke by name', '', SKILL_HEAD);
  for (const document of input.skills) {
    const meta = parseFrontmatter(document.text, SKILL_FIELDS).meta;
    // A skill is a DIRECTORY; `SKILL.md` is an implementation detail no roster should show.
    const dir = document.file.target.replace(/\/[^/]+$/, '');
    lines.push(`| [${dir.replace(/^.*\//, '')}](${target}/${dir}) | ${
      meta?.description ? summarize(meta.description) : '⚠ needs frontmatter'} |`);
  }

  // No separator rule between them. A `---` line is indistinguishable from a frontmatter fence — the
  // thing this render exists to remove — and in markdown it can also turn the line above it into a
  // heading. The provenance comment and a blank line separate them, and each rule opens with its own.
  for (const document of input.rules) {
    lines.push(
      '',
      makeHeader(document.file.pack, document.file.source, input.version),
      '',
      bodyOf(document.text),
    );
  }

  return lines.join('\n');
}

/**
 * One rule's body, read back out of a rendered region.
 *
 * 🔴 This is what keeps drift and `upstream` **per rule** inside one span. Without it the region is a
 * single artefact: a person who improves one sentence has drifted all eight rules at once, and
 * `daoris upstream <file>` has nothing to extract. It finds the rule by its PROVENANCE line — the
 * same line `planSync` compares bodies against — and returns everything up to the next one.
 *
 * @param source `<pack>/<source>`, exactly as the provenance header spells it.
 * @returns the body, or null when this region does not carry that rule.
 */
export function tierRuleBody(region: string, source: string): string | null {
  const lines = region.split('\n');
  const marker = `<!-- daoris: ${source} @`;

  const start = lines.findIndex((line) => line.startsWith(marker));
  if (start === -1) return null;

  // Up to the next provenance line, or the end. A separator immediately before it belongs to the
  // NEXT rule's frame, not to this one's body.
  let end = lines.length;
  for (let at = start + 1; at < lines.length; at += 1) {
    if (lines[at]!.startsWith('<!-- daoris: ')) {
      end = at;
      break;
    }
  }

  return lines.slice(start + 1, end).join('\n').trim();
}
