using Daoris.Knowledge;

namespace Daoris.Service.Tests;

/// <summary>
/// A deployment may name a repository's documents folder and its generated index (ORIENT1c): each document
/// split at its headings, as a log is, and each row of the index one entry, so a search for where something
/// is lands on the row that says so rather than on a table of ninety-nine.
/// </summary>
public sealed class CheckoutDocumentsTests : IDisposable
{
    private readonly string _root = Path.Combine(
        Path.GetTempPath(), "daoris-documents-" + Guid.NewGuid().ToString("N")[..8]);

    private void Write(string relative, string content)
    {
        var file = Path.Combine(_root, relative.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(file)!);
        File.WriteAllText(file, content);
    }

    public void Dispose()
    {
        if (Directory.Exists(_root)) Directory.Delete(_root, recursive: true);
    }

    private const string Routes = """
        # Bridge routes

        Generated by a tool; never edit by hand. Every route the page sends.

        ## DAORIS.DRIVER (2)

        | Route | Handler | Sent by |
        |---|---|---|
        | `SESSION_GO_ON_NEW` | `DriverModule.Sessions.cs:97` SessionGoOnNewAsync | `bridge/sessions.ts:232` useGoOnNew |
        | `STATE` | `DriverModule.cs:38` | — |

        ## DAORIS.BROWSER (1)

        | Route | Handler | Sent by |
        |---|---|---|
        | `STATE` | `BrowserModule.cs:38` | `bridge/browser.ts:45` useBrowserSettings |
        """;

    private const string Outline = """
        # Outline of `src/Widget.cs`

        Generated; never edit by hand.

        - 4-40 class Widget
          - 9-12 Widget()
          - 15-30 CountAsync()
        - 42-50 record Part
        """;

    private const string Design = """
        # The probe lock design

        Why the probe holds a lock, in one page.

        ## The lock

        One probe at a time holds the folder.

        ## Rejected

        A lock per file.
        """;

    [Fact]
    public void Each_row_of_an_index_table_is_one_entry_titled_by_its_first_cell_with_its_cells_labelled()
    {
        Write("docs/index/routes.md", Routes);

        var entries = new RepositoryScanner(documents: null, index: "docs/index").Scan(_root);

        var row = Assert.Single(entries, e => e.Title == "SESSION_GO_ON_NEW");
        // The index's own kind (ORIENT2e), as a declared index's sections are: asked for by `index`.
        Assert.Equal(EntryKind.Index, row.Kind);
        Assert.Equal(Provenance.Local, row.Provenance);
        Assert.Equal("docs/index/routes.md", row.RelativePath);
        Assert.Contains("Handler: `DriverModule.Sessions.cs:97` SessionGoOnNewAsync", row.Body);
        Assert.Contains("Sent by: `bridge/sessions.ts:232` useGoOnNew", row.Body);
        // The section the row sits in travels with it: a search for the module's name finds its routes.
        Assert.Contains("DAORIS.DRIVER (2)", row.Body);
        Assert.Contains("Bridge routes", row.Body);
    }

    [Fact]
    public void Two_rows_with_one_title_in_two_sections_are_two_entries_with_ids_of_their_own()
    {
        Write("docs/index/routes.md", Routes);

        var states = new RepositoryScanner(documents: null, index: "docs/index").Scan(_root)
            .Where(e => e.Title == "STATE").ToList();

        Assert.Equal(2, states.Count);
        Assert.Equal(2, states.Select(e => e.Id).Distinct().Count());
        Assert.Contains(states, e => e.Body.Contains("BrowserModule.cs:38"));
        // A cell with nothing in it (`—`) is still said; a missing one is not invented.
        Assert.Contains(states, e => e.Body.Contains("Sent by: —"));
    }

    [Fact]
    public void An_index_file_s_prose_is_one_entry_titled_by_its_heading()
    {
        Write("docs/index/routes.md", Routes);

        var entries = new RepositoryScanner(documents: null, index: "docs/index").Scan(_root);

        var prose = Assert.Single(entries, e => e.Title == "Bridge routes");
        Assert.Contains("Every route the page sends.", prose.Body);
        Assert.DoesNotContain("SESSION_GO_ON_NEW", prose.Body);
    }

    [Fact]
    public void Each_item_of_an_index_list_is_one_entry_that_names_the_items_above_it()
    {
        Write("docs/index/outlines/src/Widget.cs.md", Outline);

        var entries = new RepositoryScanner(documents: null, index: "docs/index").Scan(_root);

        var method = Assert.Single(entries, e => e.Title == "15-30 CountAsync()");
        Assert.Equal("docs/index/outlines/src/Widget.cs.md", method.RelativePath);
        Assert.Contains("4-40 class Widget", method.Body);
        Assert.Contains("Outline of `src/Widget.cs`", method.Body);
        // A sibling at the outer level is under nothing but the file.
        var record = Assert.Single(entries, e => e.Title == "42-50 record Part");
        Assert.DoesNotContain("class Widget", record.Body);
    }

    [Fact]
    public void A_document_is_split_at_its_headings_with_its_opening_titled_by_its_first_heading()
    {
        Write("docs/2026-10-01-probe-design.md", Design);

        var entries = new RepositoryScanner(documents: "docs", index: null).Scan(_root);

        var opening = Assert.Single(entries, e => e.Title == "The probe lock design");
        Assert.Contains("Why the probe holds a lock", opening.Body);
        var section = Assert.Single(entries, e => e.Title == "The lock");
        Assert.Equal("docs/2026-10-01-probe-design.md", section.RelativePath);
        Assert.Equal("One probe at a time holds the folder.", section.Body);
        Assert.Single(entries, e => e.Title == "Rejected");
    }

    /// <summary>One file is one place in the index: a file a role already read is never read again as a document.</summary>
    [Fact]
    public void A_document_a_role_already_read_is_not_read_again_and_the_index_is_not_split_at_headings()
    {
        Write("docs/FIX-LOG.md", "# Fixes\n\n## 2026-10-01 a fix\n\nIt broke.\n");
        Write("docs/decisions/D1.md", "## D1 — the first\n\nDecided.\n");
        Write("daoris.json", """{ "source": "s", "documents": { "decisions": "docs/decisions" } }""");
        Write("docs/index/routes.md", Routes);
        Write("docs/design.md", Design);

        var entries = new RepositoryScanner(documents: "docs", index: "docs/index").Scan(_root);

        Assert.Equal(entries.Count, entries.Select(e => e.Id).Distinct().Count());
        Assert.Single(entries, e => e.RelativePath == "docs/FIX-LOG.md");
        Assert.Equal(EntryKind.Fix, entries.Single(e => e.RelativePath == "docs/FIX-LOG.md").Kind);
        Assert.Equal(EntryKind.Decision, Assert.Single(entries, e => e.RelativePath == "docs/decisions/D1.md").Kind);
        // The index's tables are rows, not a section of ninety-nine.
        Assert.DoesNotContain(entries, e => e.RelativePath == "docs/index/routes.md" && e.Title == "DAORIS.DRIVER (2)");
    }

    /// <summary>Opt-in: a deployment that names neither folder reads what it always read.</summary>
    [Fact]
    public void A_scanner_that_names_no_folder_reads_no_document_and_no_index()
    {
        Write("docs/index/routes.md", Routes);
        Write("docs/design.md", Design);

        var entries = new RepositoryScanner().Scan(_root);

        Assert.DoesNotContain(entries, e => e.RelativePath.StartsWith("docs/", StringComparison.Ordinal));
    }

    [Fact]
    public void A_pipe_inside_code_does_not_split_a_cell()
    {
        Write("docs/index/verbs.md", """
            # Verbs

            | Verb | Command |
            |---|---|
            | `pick` | `a \| b` and `c|d` |
            """);

        var row = Assert.Single(
            new RepositoryScanner(documents: null, index: "docs/index").Scan(_root), e => e.Title == "pick");

        Assert.Contains("Command: `a \\| b` and `c|d`", row.Body);
    }
}
