using Daoris.Knowledge;

namespace Daoris.Service.Tests;

/// <summary>
/// The declared index of where things are (ORIENT2e; D151 §6, `docs/2026-10-04-orientation-everywhere-design.md`
/// §3.1–§3.2): every markdown file in the folder the declared README is in, split at its headings, as entries of
/// the kind <see cref="EntryKind.Index"/>, each keeping the lines of its file it is.
/// </summary>
/// <remarks>
/// An index row names lines in another file (an outline's <c>412-417 test …</c> names the source's lines). The
/// entry's own lines are where the row sits in the index, which is what a hit names and a range reads.
/// </remarks>
public sealed class IndexEntriesTests : IDisposable
{
    private readonly string _root = Path.Combine(
        Path.GetTempPath(), "daoris-index-" + Guid.NewGuid().ToString("N")[..8]);

    public void Dispose()
    {
        if (Directory.Exists(_root)) Directory.Delete(_root, recursive: true);
    }

    private void Write(string relative, string content)
    {
        var file = Path.Combine(_root, relative.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(file)!);
        File.WriteAllText(file, content);
    }

    private void Declare(string documents) =>
        Write("daoris.json", $$"""{"source":"s","packs":[],"documents":{{documents}}}""");

    private static List<KnowledgeEntry> Index(IEnumerable<KnowledgeEntry> entries) =>
        entries.Where(e => e.Kind == EntryKind.Index).ToList();

    private const string Readme =
        "# Where things are\n"                                  // 1
        + "\n"                                                  // 2
        + "Generated by `node tools/index.mjs`; never edit by hand.\n" // 3
        + "\n"                                                  // 4
        + "| File | Answers |\n"                                // 5
        + "|---|---|\n"                                         // 6
        + "| `routes.md` | which handler answers a route |\n"   // 7
        + "\n"                                                  // 8
        + "## Kept by hand\n"                                   // 9
        + "\n"                                                  // 10
        + "None.\n";                                            // 11

    private const string Routes =
        "# Bridge routes\n"                                     // 1
        + "\n"                                                  // 2
        + "## DAORIS.DRIVER (2)\n"                              // 3
        + "\n"                                                  // 4
        + "| Route | Handler |\n"                              // 5
        + "|---|---|\n"                                         // 6
        + "| `SESSION_GO_ON_NEW` | `DriverModule.Sessions.cs:97` |\n" // 7
        + "| `STATE` | `DriverModule.cs:38` |\n"               // 8
        + "\n"                                                  // 9
        + "### Kept apart\n"                                    // 10
        + "\n"                                                  // 11
        + "| Route | Handler |\n"                              // 12
        + "|---|---|\n"                                         // 13
        + "| `STATE` | `BrowserModule.cs:38` |\n";             // 14

    private const string Outline =
        "# Outline of `src/Widget.cs`\n"                        // 1
        + "\n"                                                  // 2
        + "Generated; never edit by hand.\n"                    // 3
        + "\n"                                                  // 4
        + "- 4-40 class Widget\n"                               // 5
        + "  - 9-12 Widget()\n"                                 // 6
        + "  - 412-417 test CountAsync\n";                      // 7

    private void Family()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md", Readme);
        Write("docs/index/routes.md", Routes);
        Write("docs/index/outlines/src/Widget.cs.md", Outline);
    }

    /// <summary>
    /// ORIENT2e's proof, with ORIENT2h's rows: each heading of each file in the index's folder, and below it, is an
    /// entry of the index's own kind, the repository's own, titled by the headings above it and keeping the lines
    /// its text is; each table row is an entry of its own, titled by its section's headings and its label, naming
    /// its line. A section that is only a table is its rows, and its header names no entry.
    /// </summary>
    [Fact]
    public void The_declared_index_is_read_at_its_headings_and_its_tables_rows_as_index_entries_that_keep_their_lines()
    {
        Family();

        var index = Index(new RepositoryScanner().Scan(_root));

        Assert.Equal(
            [
                "Bridge routes › DAORIS.DRIVER (2) › Kept apart › STATE @ docs/index/routes.md:14",
                "Bridge routes › DAORIS.DRIVER (2) › SESSION_GO_ON_NEW @ docs/index/routes.md:7",
                "Bridge routes › DAORIS.DRIVER (2) › STATE @ docs/index/routes.md:8",
                "Outline of `src/Widget.cs` @ docs/index/outlines/src/Widget.cs.md:3-7",
                "Where things are @ docs/index/README.md:3",
                "Where things are › Kept by hand @ docs/index/README.md:11",
                "Where things are › routes.md @ docs/index/README.md:7",
            ],
            index.Select(e => $"{e.Title} @ {e.RelativePath}:{e.Lines}").Order(StringComparer.Ordinal).ToList());
        Assert.All(index, e => Assert.Equal(Provenance.Local, e.Provenance));
        Assert.Equal(index.Count, index.Select(e => e.Id).Distinct().Count());
    }

    /// <summary>
    /// The entry's lines are its place in the index, never the lines its rows name: an outline's row names the
    /// source file's lines, and the body keeps them as written for the session to open there.
    /// </summary>
    [Fact]
    public void An_outline_s_lines_are_where_it_sits_in_the_index_not_the_lines_its_rows_name()
    {
        Family();

        var outline = Assert.Single(Index(new RepositoryScanner().Scan(_root)), e => e.RelativePath.EndsWith("Widget.cs.md"));

        Assert.Equal(new LineSpan(3, 7), outline.Lines);
        Assert.Contains("412-417 test CountAsync", outline.Body);
        // The body is the file's lines 3 to 7, as written: line i of the body is line 3 + i of the file.
        var file = File.ReadAllText(Path.Combine(_root, "docs", "index", "outlines", "src", "Widget.cs.md")).Split('\n');
        Assert.Equal(file[2..7], outline.Body.Split('\n'));
    }

    /// <summary>A file that opens with blank lines keeps its line numbers: the reader counts what it trimmed.</summary>
    [Fact]
    public void Lines_are_counted_from_the_file_s_first_line_whatever_opens_it()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md", "\n\n# Fixtures\n\n- `Stand` at `src/Stand.cs:3`\n");

        var only = Assert.Single(Index(new RepositoryScanner().Scan(_root)));

        Assert.Equal("Fixtures", only.Title);
        Assert.Equal(new LineSpan(5, 5), only.Lines);
    }

    /// <summary>Text before the first heading is an entry of its own, titled by the file's path.</summary>
    [Fact]
    public void Text_before_any_heading_is_titled_by_its_path()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md", "Generated; never edit.\n\n# Where things are\n\nThe rows.\n");

        var index = Index(new RepositoryScanner().Scan(_root));

        Assert.Equal(
            ["docs/index/README.md @ 1", "Where things are @ 5"],
            index.Select(e => $"{e.Title} @ {e.Lines}").ToList());
    }

    /// <summary>
    /// The folder the README is in: a markdown file beside the folder is not the index, and a declaration of a
    /// README at the repository's root reads only that file, never every file in the repository.
    /// </summary>
    [Fact]
    public void Only_the_folder_the_declared_readme_is_in_is_read_and_a_root_readme_alone()
    {
        Family();
        Write("docs/design.md", "# A design\n\n## Why\n\nBecause.\n");

        Assert.DoesNotContain(Index(new RepositoryScanner().Scan(_root)), e => e.RelativePath == "docs/design.md");

        Declare("""{"index":"INDEX.md"}""");
        Write("INDEX.md", "# Where things are\n\nThe rows.\n");
        Write("NOTES.md", "# Notes\n\nNot the index.\n");

        Assert.Equal(["INDEX.md"], Index(new RepositoryScanner().Scan(_root)).Select(e => e.RelativePath).Distinct().ToList());
    }

    /// <summary>A declared folder is read as the folder the README would be in.</summary>
    [Fact]
    public void A_declared_folder_is_read_as_the_index_s_folder()
    {
        Family();
        Declare("""{"index":"docs/index"}""");

        Assert.Equal(3, Index(new RepositoryScanner().Scan(_root)).Select(e => e.RelativePath).Distinct().Count());
    }

    /// <summary>A declared index the disk does not hold reads nothing: the repository's own check names it missing.</summary>
    [Fact]
    public void A_declared_index_that_is_not_there_reads_nothing()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/elsewhere/README.md", "# Where things are\n\nThe rows.\n");

        Assert.Empty(Index(new RepositoryScanner().Scan(_root)));
    }

    /// <summary>
    /// An undeclared folder named like an index is not the index: the role is declared, never guessed, as the
    /// router is (DOC5).
    /// </summary>
    [Fact]
    public void An_undeclared_index_is_not_guessed()
    {
        Write("daoris.json", """{"source":"s","packs":[]}""");
        Write("docs/index/README.md", Readme);

        Assert.Empty(Index(new RepositoryScanner().Scan(_root)));
    }

    /// <summary>
    /// One file is one place in the index (REV3): a deployment's documents folder never reads the declared index
    /// again, as a document or as anything else.
    /// </summary>
    [Fact]
    public void A_deployment_s_documents_never_read_the_declared_index_again()
    {
        Family();

        var entries = new RepositoryScanner(documents: "docs").Scan(_root);

        Assert.DoesNotContain(entries, e => e.Kind != EntryKind.Index && e.RelativePath.StartsWith("docs/index/", StringComparison.Ordinal));
        Assert.Equal(7, Index(entries).Count);
        Assert.All(Index(entries), e => Assert.NotNull(e.Lines));
    }

    /// <summary>
    /// A deployment that names the declared index's folder as its own index (ORIENT1c) reads it a row at a time,
    /// as it chose for that folder, still as the index's kind; every file once, so no section is read beside the
    /// rows.
    /// </summary>
    [Theory]
    [InlineData(null)]
    [InlineData("docs")]
    public void A_deployment_that_names_the_index_s_folder_reads_it_a_row_at_a_time(string? documents)
    {
        Family();

        var entries = new RepositoryScanner(documents, index: "docs/index").Scan(_root);

        var under = entries.Where(e => e.RelativePath.StartsWith("docs/index/", StringComparison.Ordinal)).ToList();
        Assert.All(under, e => Assert.Equal(EntryKind.Index, e.Kind));
        Assert.Contains(under, e => e.Title == "SESSION_GO_ON_NEW");
        Assert.DoesNotContain(under, e => e.Title.StartsWith("Bridge routes ›", StringComparison.Ordinal));
        Assert.Equal(entries.Count, entries.Select(e => e.Id).Distinct().Count());
    }

    /// <summary>A file a role already read (a router inside the index's folder) stays that role's.</summary>
    [Fact]
    public void A_file_a_role_read_is_not_read_again_as_the_index()
    {
        Family();
        Declare("""{"index":"docs/index/README.md","router":"docs/index/routes.md"}""");

        var entries = new RepositoryScanner().Scan(_root);

        Assert.Single(entries, e => e.RelativePath == "docs/index/routes.md");
        Assert.DoesNotContain(Index(entries), e => e.RelativePath == "docs/index/routes.md");
    }

    /// <summary>The kind is asked for by name, as every other kind is.</summary>
    [Fact]
    public void The_kind_is_asked_for_as_index()
    {
        Assert.Equal(new HashSet<EntryKind> { EntryKind.Index }, KnowledgeQuery.ParseKinds("index"));
        Assert.Contains("task, index", Assert.Throws<ArgumentException>(() => KnowledgeQuery.ParseKinds("indexes")).Message);
    }

    // ── a long table, a row at a time (ORIENT2h) ────────────────────────────────────────────────

    /// <summary>
    /// Routes in the shape of this repository's own index: short sections of a few routes each, as its log,
    /// registry, remotes, terminal, update and windows modules are, and one of 102, the row asked for inside it.
    /// </summary>
    private static (string Text, int Line) LongRoutes()
    {
        var lines = new List<string>
        {
            "# Bridge routes",
            "",
            "Generated; never edit by hand. Every route the page sends a module, the handler that answers it and the "
            + "bridge function that sends it.",
        };
        foreach (var (module, routes) in new (string, string[])[]
        {
            ("LOG", ["EVENT", "LINES", "OPEN_FOLDER"]),
            ("REGISTRY", ["PICK_FOLDER", "WRITE_DECLARATION"]),
            ("REMOTES", ["REMOVE", "SET", "STATE"]),
            ("TERMINAL", ["CLOSE", "INPUT", "OPEN", "RESIZE", "SHELLS"]),
            ("UPDATE", ["DISMISS", "SET", "STATE"]),
            ("WINDOWS", ["OPEN", "OPEN_BROWSER", "SET_THEME"]),
        })
        {
            var file = module[0] + module[1..].ToLowerInvariant();
            lines.AddRange(["", $"## DAORIS.{module} ({routes.Length})", "", "| Route | Handler | Sent by |", "|---|---|---|"]);
            lines.AddRange(routes.Select((route, n) =>
                $"| `{route}` | `{file}Module.cs:{40 + n}` | `bridge/{module.ToLowerInvariant()}.ts:{20 + n}` use{file}{n} |"));
        }

        string[] sessions =
        [
            "SESSION_ARCHIVE", "SESSION_DELETE", "SESSION_DIFF", "SESSION_FILE", "SESSION_FILES", "SESSION_GO_AHEAD",
            "SESSION_GO_ON_NEW", "SESSION_GROUPS", "SESSION_HISTORY", "SESSION_INPUT", "SESSION_OPENINGS",
            "SESSION_OPTIONS", "SESSION_QUEUE", "SESSION_SEARCH", "SESSION_START_FROM", "SESSION_STREAMS",
            "STOP_SESSION", "TAIL_SESSION", "RESOLVE_SESSION", "PLUGIN_NEW",
        ];
        lines.AddRange(["", "## DAORIS.DRIVER (102)", "", "| Route | Handler | Sent by |", "|---|---|---|"]);
        var asked = 0;
        for (var n = 0; n < 102; n++)
        {
            var route = n < sessions.Length ? sessions[n] : $"WORK_STEP{n}";
            var words = string.Concat(route.Split('_').Select(word => word[0] + word[1..].ToLowerInvariant()));
            if (route == "SESSION_GO_ON_NEW") asked = lines.Count + 1;
            lines.Add($"| `{route}` | `DriverModule.Sessions.cs:{10 + n * 3}` {words}Async | `bridge/sessions.ts:{5 + n * 2}` use{words} |");
        }

        return (string.Join('\n', lines) + "\n", asked);
    }

    /// <summary>Outlines that name sessions throughout, as a driver's outlines do, so the words are common ones.</summary>
    private void SessionOutlines()
    {
        foreach (var file in new[] { "Sessions", "SessionLedger", "SessionGroups", "ChatRunner" })
        {
            Write($"docs/index/outlines/src/{file}.cs.md",
                $"# Outline of `src/{file}.cs`\n\nGenerated; never edit by hand.\n\n- 10-400 class {file}\n"
                + "  - 20-40 NewSessionAsync()\n  - 41-60 SessionStateAsync()\n  - 61-80 GoOnAsync()\n");
        }
    }

    /// <summary>
    /// The row's proof: a declared index with one long table and several short sections answers a route question
    /// with the route's row first, by words alone (BM25, as a deployment with no model answers), naming its line.
    /// Read at its headings, the 102-row section lost to the short sections: one matching row weighed against a
    /// long section (ORIENT2e's measurement, ORIENT1c's finding).
    /// </summary>
    [Fact]
    public async Task A_route_question_lands_on_the_route_s_row_in_a_long_table_naming_its_line()
    {
        var (routes, line) = LongRoutes();
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md", Readme);
        Write("docs/index/routes.md", routes);
        SessionOutlines();

        var entries = new RepositoryScanner().Scan(_root);
        var database = Path.Combine(_root, "knowledge.db");
        try
        {
            await using var store = await SqliteKnowledgeStore.OpenAsync(database);
            await store.ReplaceRepositoryAsync(entries[0].Repository, entries);

            var hits = await new SqliteKnowledgeSearch(store).SearchAsync(
                new KnowledgeQuery("where is the SESSION_GO_ON_NEW handler") { Kinds = new HashSet<EntryKind> { EntryKind.Index } });

            var first = hits[0];
            Assert.Equal("Bridge routes › DAORIS.DRIVER (102) › SESSION_GO_ON_NEW", first.Entry.Title);
            Assert.Equal($"docs/index/routes.md:{line}", $"{first.Entry.RelativePath}:{first.Entry.Lines}");
            Assert.Equal(line, first.ExcerptLine);
            Assert.Equal(
                "| `SESSION_GO_ON_NEW` | `DriverModule.Sessions.cs:28` SessionGoOnNewAsync | `bridge/sessions.ts:17` useSessionGoOnNew |",
                first.Entry.Body);
        }
        finally
        {
            Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();
        }
    }

    /// <summary>
    /// The prose around a table stays prose, each run of it an entry of its own since an entry is one run of lines,
    /// and a second run before any heading is anchored apart from the file's opening, so no two share an id (REV3).
    /// </summary>
    [Fact]
    public void Prose_around_a_table_is_a_run_each_and_every_entry_has_its_own_id()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md",
            "Generated; never edit.\n"                          // 1
            + "\n"                                              // 2
            + "| File | Answers |\n"                            // 3
            + "|:---|---:|\n"                                   // 4
            + "| `routes.md` | the routes |\n"                  // 5
            + "Read the row, then the lines.\n"                 // 6
            + "\n"                                              // 7
            + "## Verbs\n"                                      // 8
            + "\n"                                              // 9
            + "Each verb's file.\n"                             // 10
            + "\n"                                              // 11
            + "| Verb | File |\n"                               // 12
            + "|---|---|\n"                                     // 13
            + "| `sync` | `sync.ts:5` |\n"                      // 14
            + "\n"                                              // 15
            + "Paths are under `src/`.\n");                     // 16

        var index = Index(new RepositoryScanner().Scan(_root));

        Assert.Equal(
            [
                "docs/index/README.md @ 1 #",
                "docs/index/README.md › routes.md @ 5 #docs/index/README.md › routes.md",
                "docs/index/README.md @ 6 #docs/index/README.md (2)",
                "Verbs @ 10 #Verbs",
                "Verbs › sync @ 14 #Verbs › sync",
                "Verbs @ 16 #Verbs (2)",
            ],
            index.Select(e => $"{e.Title} @ {e.Lines} #{e.Anchor}").ToList());
        Assert.Equal(index.Count, index.Select(e => e.Id).Distinct().Count());
    }

    /// <summary>
    /// A table is a header with a separator under it, as markdown reads one: a pipe with none is prose, and a table
    /// inside a fence is the fence's text. A row is labelled by its first cell with text, and a row with none names
    /// nothing; a pipe inside code is no column.
    /// </summary>
    [Fact]
    public void Only_a_table_s_rows_are_rows_each_labelled_by_its_first_cell_with_text()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md",
            "# Where things are\n"                              // 1
            + "\n"                                              // 2
            + "| not a table |\n"                               // 3
            + "\n"                                              // 4
            + "```\n"                                           // 5
            + "| Route | Handler |\n"                            // 6
            + "|---|---|\n"                                     // 7
            + "| `FENCED` | `X.cs:1` |\n"                        // 8
            + "```\n"                                           // 9
            + "\n"                                              // 10
            + "| Command | Does |\n"                            // 11
            + "|---|---|\n"                                     // 12
            + "| `git log | head` | reads the history |\n"      // 13
            + "|  | `continued.ts:4` |\n"                       // 14
            + "| | |\n");                                       // 15

        var index = Index(new RepositoryScanner().Scan(_root));

        Assert.Equal(
            [
                "Where things are @ 3-9",
                "Where things are › git log | head @ 13",
                "Where things are › continued.ts:4 @ 14",
            ],
            index.Select(e => $"{e.Title} @ {e.Lines}").ToList());
        Assert.Contains("`FENCED`", index[0].Body);
        Assert.Equal("|  | `continued.ts:4` |", index[2].Body);
    }
}
