using Daoris.Knowledge;

namespace Daoris.Service.Tests;

/// <summary>
/// The declared index of where things are (ORIENT2e; D151 §6, `docs/2026-10-04-orientation-everywhere-design.md`
/// §3.1–§3.2): every markdown file in the folder the declared README is in, split at its headings, as entries of
/// the kind <see cref="EntryKind.Index"/>, each keeping the lines of its file it is.
/// </summary>
/// <remarks>
/// An index row names lines in another file (an outline's <c>412-417 test …</c> names the source's lines). The
/// entry's own lines are where the row sits in the index, which is what a hit names and a range reads.
/// </remarks>
public sealed class IndexEntriesTests : IDisposable
{
    private readonly string _root = Path.Combine(
        Path.GetTempPath(), "daoris-index-" + Guid.NewGuid().ToString("N")[..8]);

    public void Dispose()
    {
        if (Directory.Exists(_root)) Directory.Delete(_root, recursive: true);
    }

    private void Write(string relative, string content)
    {
        var file = Path.Combine(_root, relative.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(file)!);
        File.WriteAllText(file, content);
    }

    private void Declare(string documents) =>
        Write("daoris.json", $$"""{"source":"s","packs":[],"documents":{{documents}}}""");

    private static List<KnowledgeEntry> Index(IEnumerable<KnowledgeEntry> entries) =>
        entries.Where(e => e.Kind == EntryKind.Index).ToList();

    private const string Readme =
        "# Where things are\n"                                  // 1
        + "\n"                                                  // 2
        + "Generated by `node tools/index.mjs`; never edit by hand.\n" // 3
        + "\n"                                                  // 4
        + "| File | Answers |\n"                                // 5
        + "|---|---|\n"                                         // 6
        + "| `routes.md` | which handler answers a route |\n"   // 7
        + "\n"                                                  // 8
        + "## Kept by hand\n"                                   // 9
        + "\n"                                                  // 10
        + "None.\n";                                            // 11

    private const string Routes =
        "# Bridge routes\n"                                     // 1
        + "\n"                                                  // 2
        + "## DAORIS.DRIVER (2)\n"                              // 3
        + "\n"                                                  // 4
        + "| Route | Handler |\n"                              // 5
        + "|---|---|\n"                                         // 6
        + "| `SESSION_GO_ON_NEW` | `DriverModule.Sessions.cs:97` |\n" // 7
        + "| `STATE` | `DriverModule.cs:38` |\n"               // 8
        + "\n"                                                  // 9
        + "### Kept apart\n"                                    // 10
        + "\n"                                                  // 11
        + "| Route | Handler |\n"                              // 12
        + "|---|---|\n"                                         // 13
        + "| `STATE` | `BrowserModule.cs:38` |\n";             // 14

    private const string Outline =
        "# Outline of `src/Widget.cs`\n"                        // 1
        + "\n"                                                  // 2
        + "Generated; never edit by hand.\n"                    // 3
        + "\n"                                                  // 4
        + "- 4-40 class Widget\n"                               // 5
        + "  - 9-12 Widget()\n"                                 // 6
        + "  - 412-417 test CountAsync\n";                      // 7

    private void Family()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md", Readme);
        Write("docs/index/routes.md", Routes);
        Write("docs/index/outlines/src/Widget.cs.md", Outline);
    }

    /// <summary>
    /// ORIENT2e's proof, with ORIENT2h's rows and ORIENT2h2's items: each heading of each file in the index's folder,
    /// and below it, is an entry of the index's own kind, the repository's own, titled by the headings above it and
    /// keeping the lines its text is; each table row is an entry of its own, titled by its section's headings and its
    /// label named by its column, naming its line; each list item too, titled by its parents' labels and its own. A
    /// section that is only a table is its rows, and its header names no entry.
    /// </summary>
    [Fact]
    public void The_declared_index_is_read_at_its_headings_and_its_tables_rows_as_index_entries_that_keep_their_lines()
    {
        Family();

        var index = Index(new RepositoryScanner().Scan(_root));

        Assert.Equal(
            [
                "Bridge routes › DAORIS.DRIVER (2) › Kept apart › Route: STATE @ docs/index/routes.md:14",
                "Bridge routes › DAORIS.DRIVER (2) › Route: SESSION_GO_ON_NEW @ docs/index/routes.md:7",
                "Bridge routes › DAORIS.DRIVER (2) › Route: STATE @ docs/index/routes.md:8",
                "Outline of `src/Widget.cs` @ docs/index/outlines/src/Widget.cs.md:3",
                "Outline of `src/Widget.cs` › 4-40 class Widget @ docs/index/outlines/src/Widget.cs.md:5",
                "Outline of `src/Widget.cs` › 4-40 class Widget › 412-417 test CountAsync @ docs/index/outlines/src/Widget.cs.md:7",
                "Outline of `src/Widget.cs` › 4-40 class Widget › 9-12 Widget() @ docs/index/outlines/src/Widget.cs.md:6",
                "Where things are @ docs/index/README.md:3",
                "Where things are › File: routes.md @ docs/index/README.md:7",
                "Where things are › Kept by hand @ docs/index/README.md:11",
            ],
            index.Select(e => $"{e.Title} @ {e.RelativePath}:{e.Lines}").Order(StringComparer.Ordinal).ToList());
        Assert.All(index, e => Assert.Equal(Provenance.Local, e.Provenance));
        Assert.Equal(index.Count, index.Select(e => e.Id).Distinct().Count());
    }

    /// <summary>
    /// The entry's lines are its place in the index, never the lines it names: an outline's item names the source
    /// file's lines, and the body keeps them as written for the session to open there.
    /// </summary>
    [Fact]
    public void An_outline_s_lines_are_where_it_sits_in_the_index_not_the_lines_its_rows_name()
    {
        Family();

        var outline = Index(new RepositoryScanner().Scan(_root)).Where(e => e.RelativePath.EndsWith("Widget.cs.md")).ToList();
        var item = Assert.Single(outline, e => e.Title.EndsWith("412-417 test CountAsync", StringComparison.Ordinal));

        Assert.Equal(new LineSpan(7, 7), item.Lines);
        // The body is the file's line 7, as written: the lines it names are its words, never its place.
        var file = File.ReadAllText(Path.Combine(_root, "docs", "index", "outlines", "src", "Widget.cs.md")).Split('\n');
        Assert.Equal(file[6].Trim(), item.Body);
        Assert.Equal([new LineSpan(3, 3), new LineSpan(5, 5), new LineSpan(6, 6), new LineSpan(7, 7)], outline.Select(e => e.Lines!.Value).ToList());
    }

    /// <summary>A file that opens with blank lines keeps its line numbers: the reader counts what it trimmed.</summary>
    [Fact]
    public void Lines_are_counted_from_the_file_s_first_line_whatever_opens_it()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md", "\n\n# Fixtures\n\n- `Stand` at `src/Stand.cs:3`\n");

        var only = Assert.Single(Index(new RepositoryScanner().Scan(_root)));

        Assert.Equal("Fixtures › Stand", only.Title);
        Assert.Equal(new LineSpan(5, 5), only.Lines);
    }

    /// <summary>Text before the first heading is an entry of its own, titled by the file's path.</summary>
    [Fact]
    public void Text_before_any_heading_is_titled_by_its_path()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md", "Generated; never edit.\n\n# Where things are\n\nThe rows.\n");

        var index = Index(new RepositoryScanner().Scan(_root));

        Assert.Equal(
            ["docs/index/README.md @ 1", "Where things are @ 5"],
            index.Select(e => $"{e.Title} @ {e.Lines}").ToList());
    }

    /// <summary>
    /// The folder the README is in: a markdown file beside the folder is not the index, and a declaration of a
    /// README at the repository's root reads only that file, never every file in the repository.
    /// </summary>
    [Fact]
    public void Only_the_folder_the_declared_readme_is_in_is_read_and_a_root_readme_alone()
    {
        Family();
        Write("docs/design.md", "# A design\n\n## Why\n\nBecause.\n");

        Assert.DoesNotContain(Index(new RepositoryScanner().Scan(_root)), e => e.RelativePath == "docs/design.md");

        Declare("""{"index":"INDEX.md"}""");
        Write("INDEX.md", "# Where things are\n\nThe rows.\n");
        Write("NOTES.md", "# Notes\n\nNot the index.\n");

        Assert.Equal(["INDEX.md"], Index(new RepositoryScanner().Scan(_root)).Select(e => e.RelativePath).Distinct().ToList());
    }

    /// <summary>A declared folder is read as the folder the README would be in.</summary>
    [Fact]
    public void A_declared_folder_is_read_as_the_index_s_folder()
    {
        Family();
        Declare("""{"index":"docs/index"}""");

        Assert.Equal(3, Index(new RepositoryScanner().Scan(_root)).Select(e => e.RelativePath).Distinct().Count());
    }

    /// <summary>A declared index the disk does not hold reads nothing: the repository's own check names it missing.</summary>
    [Fact]
    public void A_declared_index_that_is_not_there_reads_nothing()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/elsewhere/README.md", "# Where things are\n\nThe rows.\n");

        Assert.Empty(Index(new RepositoryScanner().Scan(_root)));
    }

    /// <summary>
    /// An undeclared folder named like an index is not the index: the role is declared, never guessed, as the
    /// router is (DOC5).
    /// </summary>
    [Fact]
    public void An_undeclared_index_is_not_guessed()
    {
        Write("daoris.json", """{"source":"s","packs":[]}""");
        Write("docs/index/README.md", Readme);

        Assert.Empty(Index(new RepositoryScanner().Scan(_root)));
    }

    /// <summary>
    /// One file is one place in the index (REV3): a deployment's documents folder never reads the declared index
    /// again, as a document or as anything else.
    /// </summary>
    [Fact]
    public void A_deployment_s_documents_never_read_the_declared_index_again()
    {
        Family();

        var entries = new RepositoryScanner(documents: "docs").Scan(_root);

        Assert.DoesNotContain(entries, e => e.Kind != EntryKind.Index && e.RelativePath.StartsWith("docs/index/", StringComparison.Ordinal));
        Assert.Equal(10, Index(entries).Count);
        Assert.All(Index(entries), e => Assert.NotNull(e.Lines));
    }

    /// <summary>
    /// A deployment that names the declared index's folder as its own index (ORIENT1c) reads it a row at a time,
    /// as it chose for that folder, still as the index's kind; every file once, so no section is read beside the
    /// rows.
    /// </summary>
    [Theory]
    [InlineData(null)]
    [InlineData("docs")]
    public void A_deployment_that_names_the_index_s_folder_reads_it_a_row_at_a_time(string? documents)
    {
        Family();

        var entries = new RepositoryScanner(documents, index: "docs/index").Scan(_root);

        var under = entries.Where(e => e.RelativePath.StartsWith("docs/index/", StringComparison.Ordinal)).ToList();
        Assert.All(under, e => Assert.Equal(EntryKind.Index, e.Kind));
        Assert.Contains(under, e => e.Title == "SESSION_GO_ON_NEW");
        Assert.DoesNotContain(under, e => e.Title.StartsWith("Bridge routes ›", StringComparison.Ordinal));
        Assert.Equal(entries.Count, entries.Select(e => e.Id).Distinct().Count());
    }

    /// <summary>A file a role already read (a router inside the index's folder) stays that role's.</summary>
    [Fact]
    public void A_file_a_role_read_is_not_read_again_as_the_index()
    {
        Family();
        Declare("""{"index":"docs/index/README.md","router":"docs/index/routes.md"}""");

        var entries = new RepositoryScanner().Scan(_root);

        Assert.Single(entries, e => e.RelativePath == "docs/index/routes.md");
        Assert.DoesNotContain(Index(entries), e => e.RelativePath == "docs/index/routes.md");
    }

    /// <summary>The kind is asked for by name, as every other kind is.</summary>
    [Fact]
    public void The_kind_is_asked_for_as_index()
    {
        Assert.Equal(new HashSet<EntryKind> { EntryKind.Index }, KnowledgeQuery.ParseKinds("index"));
        Assert.Contains("task, index", Assert.Throws<ArgumentException>(() => KnowledgeQuery.ParseKinds("indexes")).Message);
    }

    // ── a long table, a row at a time (ORIENT2h) ────────────────────────────────────────────────

    /// <summary>
    /// Routes in the shape of this repository's own index: short sections of a few routes each, as its log,
    /// registry, remotes, terminal, update and windows modules are, and one of 102, the row asked for inside it.
    /// </summary>
    private static (string Text, int Line) LongRoutes()
    {
        var lines = new List<string>
        {
            "# Bridge routes",
            "",
            "Generated; never edit by hand. Every route the page sends a module, the handler that answers it and the "
            + "bridge function that sends it.",
        };
        foreach (var (module, routes) in new (string, string[])[]
        {
            ("LOG", ["EVENT", "LINES", "OPEN_FOLDER"]),
            ("REGISTRY", ["PICK_FOLDER", "WRITE_DECLARATION"]),
            ("REMOTES", ["REMOVE", "SET", "STATE"]),
            ("TERMINAL", ["CLOSE", "INPUT", "OPEN", "RESIZE", "SHELLS"]),
            ("UPDATE", ["DISMISS", "SET", "STATE"]),
            ("WINDOWS", ["OPEN", "OPEN_BROWSER", "SET_THEME"]),
        })
        {
            var file = module[0] + module[1..].ToLowerInvariant();
            lines.AddRange(["", $"## DAORIS.{module} ({routes.Length})", "", "| Route | Handler | Sent by |", "|---|---|---|"]);
            lines.AddRange(routes.Select((route, n) =>
                $"| `{route}` | `{file}Module.cs:{40 + n}` | `bridge/{module.ToLowerInvariant()}.ts:{20 + n}` use{file}{n} |"));
        }

        string[] sessions =
        [
            "SESSION_ARCHIVE", "SESSION_DELETE", "SESSION_DIFF", "SESSION_FILE", "SESSION_FILES", "SESSION_GO_AHEAD",
            "SESSION_GO_ON_NEW", "SESSION_GROUPS", "SESSION_HISTORY", "SESSION_INPUT", "SESSION_OPENINGS",
            "SESSION_OPTIONS", "SESSION_QUEUE", "SESSION_SEARCH", "SESSION_START_FROM", "SESSION_STREAMS",
            "STOP_SESSION", "TAIL_SESSION", "RESOLVE_SESSION", "PLUGIN_NEW",
        ];
        lines.AddRange(["", "## DAORIS.DRIVER (102)", "", "| Route | Handler | Sent by |", "|---|---|---|"]);
        var asked = 0;
        for (var n = 0; n < 102; n++)
        {
            var route = n < sessions.Length ? sessions[n] : $"WORK_STEP{n}";
            var words = string.Concat(route.Split('_').Select(word => word[0] + word[1..].ToLowerInvariant()));
            if (route == "SESSION_GO_ON_NEW") asked = lines.Count + 1;
            lines.Add($"| `{route}` | `DriverModule.Sessions.cs:{10 + n * 3}` {words}Async | `bridge/sessions.ts:{5 + n * 2}` use{words} |");
        }

        return (string.Join('\n', lines) + "\n", asked);
    }

    /// <summary>Outlines that name sessions throughout, as a driver's outlines do, so the words are common ones.</summary>
    private void SessionOutlines()
    {
        foreach (var file in new[] { "Sessions", "SessionLedger", "SessionGroups", "ChatRunner" })
        {
            Write($"docs/index/outlines/src/{file}.cs.md",
                $"# Outline of `src/{file}.cs`\n\nGenerated; never edit by hand.\n\n- 10-400 class {file}\n"
                + "  - 20-40 NewSessionAsync()\n  - 41-60 SessionStateAsync()\n  - 61-80 GoOnAsync()\n");
        }
    }

    /// <summary>
    /// The row's proof: a declared index with one long table and several short sections answers a route question
    /// with the route's row first, by words alone (BM25, as a deployment with no model answers), naming its line.
    /// Read at its headings, the 102-row section lost to the short sections: one matching row weighed against a
    /// long section (ORIENT2e's measurement, ORIENT1c's finding).
    /// </summary>
    [Fact]
    public async Task A_route_question_lands_on_the_route_s_row_in_a_long_table_naming_its_line()
    {
        var (routes, line) = LongRoutes();
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md", Readme);
        Write("docs/index/routes.md", routes);
        SessionOutlines();

        var entries = new RepositoryScanner().Scan(_root);
        var database = Path.Combine(_root, "knowledge.db");
        try
        {
            await using var store = await SqliteKnowledgeStore.OpenAsync(database);
            await store.ReplaceRepositoryAsync(entries[0].Repository, entries);

            var hits = await new SqliteKnowledgeSearch(store).SearchAsync(
                new KnowledgeQuery("where is the SESSION_GO_ON_NEW handler") { Kinds = new HashSet<EntryKind> { EntryKind.Index } });

            var first = hits[0];
            Assert.Equal("Bridge routes › DAORIS.DRIVER (102) › Route: SESSION_GO_ON_NEW", first.Entry.Title);
            Assert.Equal($"docs/index/routes.md:{line}", $"{first.Entry.RelativePath}:{first.Entry.Lines}");
            Assert.Equal(line, first.ExcerptLine);
            Assert.Equal(
                "| `SESSION_GO_ON_NEW` | `DriverModule.Sessions.cs:28` SessionGoOnNewAsync | `bridge/sessions.ts:17` useSessionGoOnNew |",
                first.Entry.Body);
        }
        finally
        {
            Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();
        }
    }

    /// <summary>
    /// A question that names what a row is, in its column's word, reaches the row: the header is no line of the row,
    /// so the title names the label's column. Without it, <i>sync verb</i> ranked outlines that say both words above
    /// the <c>sync</c> row, which says one (measured on this repository's index, D151's ORIENT2h note).
    /// </summary>
    [Fact]
    public async Task A_question_in_the_column_s_word_reaches_the_row_its_title_names_by_that_column()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md", Readme);
        Write("docs/index/verbs.md",
            "# Terminal verbs\n\nGenerated; never edit by hand. Where each terminal verb is routed and handled, by program.\n\n"
            + "## `daoris` (the CLI)\n\n| Verb | Class | Handler | Usage |\n|---|---|---|---|\n"
            + "| `analyze` | doctrine | `analyze.ts:268` commandAnalyze | what adopting would do here |\n"
            + "| `init` | doctrine | `commands.ts:55` commandInit | detect what this repo has |\n"
            + "| `sync` | doctrine | `materialize.ts:811` commandSync | materialize the manifest's packs |\n"
            + "| `check` | doctrine | `drift.ts:292` commandCheck | drift and staleness |\n"
            + "| `upstream` | doctrine | `upstream.ts:40` commandUpstream | promote a local edit |\n");
        // No class is named for the question's word (ORIENT2h2): read an item at a time, each item of such a class says
        // it twice in its title, in its file's heading and its class's label, and in a fixture this small, where half
        // the entries say "verb", the word alone decided. Left without its column, an outline's item still ranks first.
        foreach (var file in new[] { "HelpCoverageTests", "LedgerConsole", "TreesConsole" })
        {
            Write($"docs/index/outlines/src/{file}.cs.md",
                $"# Outline of `src/{file}.cs`\n\nGenerated; never edit by hand.\n\n- 10-400 class {file}\n"
                + "  - 20-40 Every verb has a door()\n  - 41-60 The sync verb's console()\n  - 61-80 Status()\n");
        }

        var entries = new RepositoryScanner().Scan(_root);
        var database = Path.Combine(_root, "knowledge.db");
        try
        {
            await using var store = await SqliteKnowledgeStore.OpenAsync(database);
            await store.ReplaceRepositoryAsync(entries[0].Repository, entries);

            var hits = await new SqliteKnowledgeSearch(store).SearchAsync(
                new KnowledgeQuery("sync verb") { Kinds = new HashSet<EntryKind> { EntryKind.Index } });

            Assert.Equal("Terminal verbs › `daoris` (the CLI) › Verb: sync @ 11", $"{hits[0].Entry.Title} @ {hits[0].Entry.Lines}");
        }
        finally
        {
            Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();
        }
    }

    /// <summary>
    /// The prose around a table stays prose, each run of it an entry of its own since an entry is one run of lines,
    /// and a second run before any heading is anchored apart from the file's opening, so no two share an id (REV3).
    /// </summary>
    [Fact]
    public void Prose_around_a_table_is_a_run_each_and_every_entry_has_its_own_id()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md",
            "Generated; never edit.\n"                          // 1
            + "\n"                                              // 2
            + "| File | Answers |\n"                            // 3
            + "|:---|---:|\n"                                   // 4
            + "| `routes.md` | the routes |\n"                  // 5
            + "Read the row, then the lines.\n"                 // 6
            + "\n"                                              // 7
            + "## Verbs\n"                                      // 8
            + "\n"                                              // 9
            + "Each verb's file.\n"                             // 10
            + "\n"                                              // 11
            + "| Verb | File |\n"                               // 12
            + "|---|---|\n"                                     // 13
            + "| `sync` | `sync.ts:5` |\n"                      // 14
            + "\n"                                              // 15
            + "Paths are under `src/`.\n");                     // 16

        var index = Index(new RepositoryScanner().Scan(_root));

        Assert.Equal(
            [
                "docs/index/README.md @ 1 #",
                "docs/index/README.md › File: routes.md @ 5 #docs/index/README.md › File: routes.md",
                "docs/index/README.md @ 6 #docs/index/README.md (2)",
                "Verbs @ 10 #Verbs",
                "Verbs › Verb: sync @ 14 #Verbs › Verb: sync",
                "Verbs @ 16 #Verbs (2)",
            ],
            index.Select(e => $"{e.Title} @ {e.Lines} #{e.Anchor}").ToList());
        Assert.Equal(index.Count, index.Select(e => e.Id).Distinct().Count());
    }

    /// <summary>
    /// A table is a header with a separator under it, as markdown reads one: a pipe with none is prose, and a table
    /// inside a fence is the fence's text. A row is labelled by its first cell with text, named by that cell's column,
    /// and a row with none names nothing; a pipe inside code is no column.
    /// </summary>
    [Fact]
    public void Only_a_table_s_rows_are_rows_each_labelled_by_its_first_cell_with_text()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md",
            "# Where things are\n"                              // 1
            + "\n"                                              // 2
            + "| not a table |\n"                               // 3
            + "\n"                                              // 4
            + "```\n"                                           // 5
            + "| Route | Handler |\n"                            // 6
            + "|---|---|\n"                                     // 7
            + "| `FENCED` | `X.cs:1` |\n"                        // 8
            + "```\n"                                           // 9
            + "\n"                                              // 10
            + "| Command | Does |\n"                            // 11
            + "|---|---|\n"                                     // 12
            + "| `git log | head` | reads the history |\n"      // 13
            + "|  | `continued.ts:4` |\n"                       // 14
            + "| | |\n");                                       // 15

        var index = Index(new RepositoryScanner().Scan(_root));

        Assert.Equal(
            [
                "Where things are @ 3-9",
                "Where things are › Command: git log | head @ 13",
                "Where things are › Does: continued.ts:4 @ 14",
            ],
            index.Select(e => $"{e.Title} @ {e.Lines}").ToList());
        Assert.Contains("`FENCED`", index[0].Body);
        Assert.Equal("|  | `continued.ts:4` |", index[2].Body);
    }

    // ── a long list, an item at a time (ORIENT2h2) ──────────────────────────────────────────────

    /// <summary>
    /// Fixtures in the shape of this repository's own index: a section per suite, one of them a list of 61 items,
    /// the item asked for inside it, and short lists beside it that name stand-ins too.
    /// </summary>
    private static (string Text, int Line) LongFixtures()
    {
        var lines = new List<string>
        {
            "# Test fixtures, stand-ins and kits",
            "",
            "Generated; never edit by hand. By suite: each helper file's types and their non-private members, each test "
            + "file's shared or stand-in types, each with its line.",
            "",
            "## `src/Driver.Tests/`",
            "",
        };
        var asked = 0;
        for (var n = 0; n < 61; n++)
        {
            if (n == 1)
            {
                asked = lines.Count + 1;
                lines.Add("- `AnswerContinuesTickTests.cs:284` class ParkStandIn");
                continue;
            }
            lines.Add((n % 3) switch
            {
                0 => $"- `Step{n}Tests.cs:{100 + n}` class StandIn (private)",
                1 => $"- `Step{n}Fixture.cs:{10 + n}` class Step{n}Fixture: Park {20 + n}, Answer {30 + n}",
                _ => $"- `Step{n}Kit.cs:{10 + n}` the fixture where step {n} is parked",
            });
        }
        foreach (var suite in new[] { "Cli/test", "Service.Tests", "Devkit.Tests", "Web/src/test" })
        {
            lines.AddRange(["", $"## `src/{suite}/`", ""]);
            lines.AddRange(Enumerable.Range(0, 3).Select(n => $"- `{suite.Replace('/', '.')}{n}.cs:{5 + n}` class StandInPark{n}"));
        }
        return (string.Join('\n', lines) + "\n", asked);
    }

    /// <summary>
    /// The row's proof (ORIENT2h2): a declared index with one long list and several short sections answers a
    /// question about one item with that item first, by words alone, naming its line. Read at its headings, the
    /// answer was the list's whole section, 61 lines for one.
    /// </summary>
    [Fact]
    public async Task An_item_question_lands_on_the_item_in_a_long_list_naming_its_line()
    {
        var (fixtures, line) = LongFixtures();
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md", Readme);
        Write("docs/index/fixtures.md", fixtures);
        SessionOutlines();

        var entries = new RepositoryScanner().Scan(_root);
        var database = Path.Combine(_root, "knowledge.db");
        try
        {
            await using var store = await SqliteKnowledgeStore.OpenAsync(database);
            await store.ReplaceRepositoryAsync(entries[0].Repository, entries);
            var search = new SqliteKnowledgeSearch(store);

            foreach (var kinds in new[] { new HashSet<EntryKind> { EntryKind.Index }, null })
            {
                var first = (await search.SearchAsync(new KnowledgeQuery("where is the fixture ParkStandIn") { Kinds = kinds }))[0];

                Assert.Equal(
                    $"Test fixtures, stand-ins and kits › `src/Driver.Tests/` › AnswerContinuesTickTests.cs:284 @ docs/index/fixtures.md:{line}",
                    $"{first.Entry.Title} @ {first.Entry.RelativePath}:{first.Entry.Lines}");
                Assert.Equal("- `AnswerContinuesTickTests.cs:284` class ParkStandIn", first.Entry.Body);
                Assert.Equal(line, first.ExcerptLine);
            }
        }
        finally
        {
            Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();
        }
    }

    /// <summary>
    /// A nested item is an entry of its own, titled by its parent's label as well as the headings above it, so read
    /// alone it keeps its place: an outline's method names its class. An item's label is its leading code span or
    /// link text where it opens with one, and its text otherwise; its continuation lines are its own.
    /// </summary>
    [Fact]
    public void A_nested_item_keeps_its_parent_s_label_in_its_title()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/outlines/src/Widget.cs.md",
            "# Outline of `src/Widget.cs`\n"                    // 1
            + "\n"                                              // 2
            + "Generated; never edit by hand.\n"                // 3
            + "\n"                                              // 4
            + "- 4-40 class Widget\n"                           // 5
            + "  - 9-12 Widget()\n"                             // 6
            + "  - 412-417 test CountAsync\n"                   // 7
            + "- [`Gadget`](src/Gadget.cs) the gadget, whose\n" // 8
            + "  line wraps\n"                                  // 9
            + "  - `Spin()` turns it\n"                         // 10
            + "    - `Spin(int)` by so many\n");                // 11
        Write("docs/index/README.md", "# Where things are\n");

        var index = Index(new RepositoryScanner().Scan(_root));

        Assert.Equal(
            [
                "Outline of `src/Widget.cs` @ 3",
                "Outline of `src/Widget.cs` › 4-40 class Widget @ 5",
                "Outline of `src/Widget.cs` › 4-40 class Widget › 9-12 Widget() @ 6",
                "Outline of `src/Widget.cs` › 4-40 class Widget › 412-417 test CountAsync @ 7",
                "Outline of `src/Widget.cs` › Gadget @ 8-9",
                "Outline of `src/Widget.cs` › Gadget › Spin() @ 10",
                "Outline of `src/Widget.cs` › Gadget › Spin() › Spin(int) @ 11",
            ],
            index.Select(e => $"{e.Title} @ {e.Lines}").ToList());
        Assert.Equal("- 412-417 test CountAsync", index[3].Body);
        Assert.Equal("- [`Gadget`](src/Gadget.cs) the gadget, whose\n  line wraps", index[4].Body);
        Assert.Equal(index.Count, index.Select(e => e.Id).Distinct().Count());
    }

    /// <summary>
    /// An item is read as markdown reads one: a line with no blank before it continues the item it follows, and after
    /// a blank only a line indented to the item's text does; a fence indented into an item is the item's, a list
    /// inside it included; an ordered item is an item, and a thematic break is none. Text of an item after its
    /// nested items is a second run of it, anchored as a repeat, since an entry is one run of lines.
    /// </summary>
    [Fact]
    public void An_item_s_continuation_lines_are_its_own_and_the_list_ends_where_markdown_ends_it()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md",
            "# Kits\n"                                          // 1
            + "\n"                                              // 2
            + "Each kit by file.\n"                             // 3
            + "\n"                                              // 4
            + "1. `setup-kit.mjs` writes the set-up,\n"         // 5
            + "lazily continued\n"                              // 6
            + "\n"                                              // 7
            + "   and a second paragraph of it\n"               // 8
            + "\n"                                              // 9
            + "   ```\n"                                        // 10
            + "   - not an item\n"                              // 11
            + "   ```\n"                                        // 12
            + "2) `proof-kit.mjs`\n"                            // 13
            + "   - `openProof` opens one\n"                    // 14
            + "\n"                                              // 15
            + "   the proof kit's own words again\n"            // 16
            + "\n"                                              // 17
            + "- - -\n"                                         // 18
            + "\n"                                              // 19
            + "After the list.\n");                             // 20

        var index = Index(new RepositoryScanner().Scan(_root));

        Assert.Equal(
            [
                "Kits @ 3 #Kits",
                "Kits › setup-kit.mjs @ 5-12 #Kits › setup-kit.mjs",
                "Kits › proof-kit.mjs @ 13 #Kits › proof-kit.mjs",
                "Kits › proof-kit.mjs › openProof @ 14 #Kits › proof-kit.mjs › openProof",
                "Kits › proof-kit.mjs @ 16 #Kits › proof-kit.mjs (2)",
                "Kits @ 18-20 #Kits (2)",
            ],
            index.Select(e => $"{e.Title} @ {e.Lines} #{e.Anchor}").ToList());
        Assert.Contains("- not an item", index[1].Body);
        Assert.Equal(index.Count, index.Select(e => e.Id).Distinct().Count());
    }

    // ── an item's id, past the lines it leads with (ORIENT2h5) ──────────────────────────────────

    /// <summary>
    /// Three generators' items, each leading with the lines it names: an outline's ranges, a fixture's line after its
    /// file, a digest's lines after its decision; and an item that leads with none. <paramref name="moved"/> is the
    /// same index after an edit above every one of those lines moved them, which also added a member.
    /// </summary>
    private void NumberedItems(bool moved)
    {
        var (shift, added) = moved ? (10, "  - 15-17 const Size\n") : (0, string.Empty);
        string Lines(int first, int last) => $"{first + shift}-{last + shift}";
        Write("docs/index/outlines/src/Widget.cs.md",
            "# Outline of `src/Widget.cs`\n\nGenerated; never edit by hand.\n\n"
            + $"- {Lines(4, 40)} class Widget\n"
            + added
            + $"  - {Lines(9, 12)} Widget()\n"
            + $"  - {Lines(412, 417)} test CountAsync\n"
            + $"  - {Lines(418, 420)} Task()\n"
            + $"  - {Lines(421, 423)} Task()\n"
            + "- [`Gadget`](src/Gadget.cs) the gadget\n"
            + "  - `Spin()` turns it\n");
        Write("docs/index/fixtures.md",
            "# Test fixtures\n\n## `src/Driver.Tests/`\n\n"
            + $"- `AnswerContinuesTickTests.cs:{284 + shift}` class ParkStandIn\n"
            + $"- `ChatGoOnTests.cs:{401 + shift}` class ChatLedger\n"
            + $"- `ChatGoOnTests.cs:{485 + shift}` class Words\n");
        Write("docs/index/decisions.md",
            "# Decisions digest\n\n## Notes (2)\n\n"
            + $"- D151:{Lines(195, 239)} ORIENT2h, built 2026-10-07: a declared index's tables are read a row at a time.\n"
            + $"- D151:{Lines(241, 253)} ORIENT2e2, built 2026-10-07: the lines travel.\n");
    }

    /// <summary>
    /// ORIENT2h5's proof: an item that leads with the lines it names keeps its id when an edit above those lines moves
    /// them, in the declared index and in a deployment's index read a row at a time alike, since an id is how a hit is
    /// fetched again and how a refresh replaces an entry rather than adding one. Its title still names the lines, which
    /// a person reads. Anchored on the title whole, every such item took a new id at every edit: between two commits of
    /// this repository's index, 1,259 items whose lines moved, and none kept its id (D151's ORIENT2h5 note).
    /// </summary>
    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void An_item_keeps_its_id_when_the_lines_it_leads_with_move(bool deployment)
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md", Readme);
        List<KnowledgeEntry> Read() =>
            Index(new RepositoryScanner(index: deployment ? "docs/index" : null).Scan(_root))
                .Where(e => e.RelativePath != "docs/index/README.md").ToList();

        NumberedItems(moved: false);
        var before = Read();
        NumberedItems(moved: true);
        var after = Read();

        Assert.Empty(before.Select(e => e.Id).Except(after.Select(e => e.Id)));
        Assert.Equal(before.Count + 1, after.Count);
        Assert.Equal(after.Count, after.Select(e => e.Id).Distinct().Count());
        Assert.Contains(after, e => e.Title.EndsWith("19-22 Widget()", StringComparison.Ordinal));
        Assert.Contains(after, e => e.Title.Contains("ChatGoOnTests.cs:495", StringComparison.Ordinal));
        Assert.Contains(after, e => e.Title.Contains("D151:251-263", StringComparison.Ordinal));
    }

    /// <summary>
    /// ORIENT2h5: an item is anchored by its title with the lines each label leads with taken out, its parents'
    /// included, since a class's range moves with every edit inside it; two that are then alike are told apart by
    /// their count, as two titles alike always were. An item that leads with no lines is anchored by its title, as it
    /// always was.
    /// </summary>
    [Fact]
    public void An_item_is_anchored_past_the_lines_its_labels_lead_with_and_titled_with_them()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md", "# Where things are\n");
        NumberedItems(moved: false);

        var index = Index(new RepositoryScanner().Scan(_root)).Where(e => e.RelativePath != "docs/index/README.md");

        Assert.Equal(
            [
                "Decisions digest › Notes (2) › D151:195-239 ORIENT2h, built 2026-10-07: a declared index's tables are read a row at a time. "
                + "#Decisions digest › Notes (2) › D151 ORIENT2h, built 2026-10-07: a declared index's tables are read a row at a time.",
                "Decisions digest › Notes (2) › D151:241-253 ORIENT2e2, built 2026-10-07: the lines travel. "
                + "#Decisions digest › Notes (2) › D151 ORIENT2e2, built 2026-10-07: the lines travel.",
                "Test fixtures › `src/Driver.Tests/` › AnswerContinuesTickTests.cs:284 #Test fixtures › `src/Driver.Tests/` › AnswerContinuesTickTests.cs",
                "Test fixtures › `src/Driver.Tests/` › ChatGoOnTests.cs:401 #Test fixtures › `src/Driver.Tests/` › ChatGoOnTests.cs",
                "Test fixtures › `src/Driver.Tests/` › ChatGoOnTests.cs:485 #Test fixtures › `src/Driver.Tests/` › ChatGoOnTests.cs (2)",
                "Outline of `src/Widget.cs` #Outline of `src/Widget.cs`",
                "Outline of `src/Widget.cs` › 4-40 class Widget #Outline of `src/Widget.cs` › class Widget",
                "Outline of `src/Widget.cs` › 4-40 class Widget › 9-12 Widget() #Outline of `src/Widget.cs` › class Widget › Widget()",
                "Outline of `src/Widget.cs` › 4-40 class Widget › 412-417 test CountAsync #Outline of `src/Widget.cs` › class Widget › test CountAsync",
                "Outline of `src/Widget.cs` › 4-40 class Widget › 418-420 Task() #Outline of `src/Widget.cs` › class Widget › Task()",
                "Outline of `src/Widget.cs` › 4-40 class Widget › 421-423 Task() #Outline of `src/Widget.cs` › class Widget › Task() (2)",
                "Outline of `src/Widget.cs` › Gadget #Outline of `src/Widget.cs` › Gadget",
                "Outline of `src/Widget.cs` › Gadget › Spin() #Outline of `src/Widget.cs` › Gadget › Spin()",
            ],
            index.Select(e => $"{e.Title} #{e.Anchor}").ToList());
    }

    /// <summary>
    /// ORIENT2h5: what counts as the lines a label leads with. Its first word, where it is a line or a range of lines
    /// or ends in one after a colon; what follows is what the item is. Anything else is the label as it is: a date, a
    /// port, a label that is only its lines.
    /// </summary>
    [Theory]
    [InlineData("695-731 PublishAsync()", "PublishAsync()")]
    [InlineData("23-50 2. The shell", "2. The shell")]
    [InlineData("AnswerContinuesTickTests.cs:284", "AnswerContinuesTickTests.cs")]
    [InlineData("AnswerContinuesTickTests.cs:284 class ParkStandIn", "AnswerContinuesTickTests.cs class ParkStandIn")]
    [InlineData("D151:195-239 ORIENT2h, built", "D151 ORIENT2h, built")]
    [InlineData(":284 class ParkStandIn", "class ParkStandIn")]
    [InlineData("PublishAsync()", "PublishAsync()")]
    [InlineData("2026-10-07 the day", "2026-10-07 the day")]
    [InlineData("localhost:8080/api the host", "localhost:8080/api the host")]
    [InlineData("12-", "12-")]
    [InlineData("695-731", "695-731")]
    [InlineData("D1:", "D1:")]
    [InlineData("x:١٢ Arabic digits", "x:١٢ Arabic digits")]
    public void A_label_s_leading_lines_are_its_first_word_s_line_or_range(string label, string anchored)
    {
        Assert.Equal(anchored, IndexRows.Unnumbered(label));
    }

    /// <summary>
    /// ORIENT2h3: a title that is literally another title's counted anchor is anchored past it. Counting titles alone
    /// gave <c>A</c>, <c>A (2)</c> and <c>A (2)</c>, two entries shared an id, and the store's insert failed the whole
    /// refresh. The anchors a title had while every id was unique are kept.
    /// </summary>
    [Fact]
    public async Task A_title_that_is_another_s_counted_anchor_gets_the_next_free_one_and_the_refresh_succeeds()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md", "# A\n\nOne.\n\n# A\n\nTwo.\n\n# A (2)\n\nThree.\n");

        var entries = new RepositoryScanner().Scan(_root);
        var database = Path.Combine(_root, "knowledge.db");
        try
        {
            await using var store = await SqliteKnowledgeStore.OpenAsync(database);
            await store.ReplaceRepositoryAsync(entries[0].Repository, entries);

            var stored = Index(await store.AllAsync()).OrderBy(e => e.Lines?.First).ToList();
            Assert.Equal(
                ["A @ 3 #A", "A @ 7 #A (2)", "A (2) @ 11 #A (2) (2)"],
                stored.Select(e => $"{e.Title} @ {e.Lines} #{e.Anchor}").ToList());
            Assert.Equal(3, stored.Select(e => e.Id).Distinct().Count());
        }
        finally
        {
            Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();
        }
    }

    /// <summary>
    /// ORIENT2h3: a fence is closed only by a fence of its own character at least as long, as CommonMark reads one. A
    /// four-backtick fence quoting a three-backtick example closed on the example's first fence, and the heading and
    /// the table inside the example became a section and a row.
    /// </summary>
    [Fact]
    public void A_longer_fence_holds_a_shorter_one_and_nothing_inside_it_is_an_entry()
    {
        Declare("""{"index":"docs/index/README.md"}""");
        Write("docs/index/README.md",
            "# Where things are\n"                              // 1
            + "\n"                                              // 2
            + "````markdown\n"                                  // 3
            + "```\n"                                           // 4
            + "## Not a heading\n"                              // 5
            + "\n"                                              // 6
            + "| Route | Handler |\n"                            // 7
            + "|---|---|\n"                                     // 8
            + "| `FENCED` | `X.cs:1` |\n"                        // 9
            + "```\n"                                           // 10
            + "````\n"                                          // 11
            + "\n"                                              // 12
            + "| Command | Does |\n"                            // 13
            + "|---|---|\n"                                     // 14
            + "| `sync` | writes the files |\n");               // 15

        var index = Index(new RepositoryScanner().Scan(_root));

        Assert.Equal(
            ["Where things are @ 3-11", "Where things are › Command: sync @ 15"],
            index.Select(e => $"{e.Title} @ {e.Lines}").ToList());
        Assert.Contains("## Not a heading", index[0].Body);
        Assert.Contains("`FENCED`", index[0].Body);
    }
}
