// The index of the on-demand tiers, out of the region (WSSETUP14a; D128 §2.2–§2.4, as D129 amends it).
//
// The region holds what the canon bounds: the rules, a pointer, the rooms and *Where things are*. The
// knowledge and skill tables grow with the repository, so they go to `<target>/INDEX.md`, which `sync`
// writes, `check` rebuilds offline and the lock names. One test per cell of §2.4's table — D19 for a
// file the canon does not ship — written before the code.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { rmSync } from 'node:fs';
import { join } from 'node:path';
import { captureError } from './_fixture.ts';
import { doc, layoutFixture, skill } from './_layout.ts';
import { writeLock } from '../src/config.ts';
import { DaorisError } from '../src/errors.ts';

const INDEX = '.claude/INDEX.md';
const pointer = (path: string) => `The knowledge and the skills, each with when it applies, are listed in [${path}](${path}), `
  + 'generated from the files: read it before a non-trivial task, and search it when it is long.';
const TEXT = /looks like a link checked out as text/;

test('index cell: not in the lock, absent — written, with both tables, and the lock names it', () => {
  const fx = layoutFixture('index-create');
  fx.repoFx.write('.claude/knowledge/ours.md', doc('ours'));
  fx.repoFx.write('.claude/skills/house/SKILL.md', skill('house'));

  const lock = fx.sync();

  const index = fx.repoFx.read(INDEX);
  assert.ok(index.startsWith('# Index\n\nGenerated by daoris from the files.'), index.slice(0, 80));
  assert.match(index, /^## Knowledge$/m);
  // Named by its path from the repository's root, as a code span: an agent opens it as written.
  assert.match(index, /^\| `\.claude\/knowledge\/storage\.md` \| w \| e \|$/m);
  assert.match(index, /^\| `\.claude\/knowledge\/ours\.md` _\(local\)_ \| w \| e \|$/m);
  assert.match(index, /^## Skills$/m);
  assert.match(index, /^\| `\.claude\/skills\/finder\/SKILL\.md` \| Use when finder is wanted\. \|$/m);
  assert.match(index, /^\| `\.claude\/skills\/house\/SKILL\.md` _\(local\)_ \| Use when house is wanted\. \|$/m);
  assert.ok(index.endsWith('|\n'), 'one newline at the end, as every write');
  assert.equal(lock.index, INDEX);
  assert.equal(fx.cli('check').code, 0, fx.cli('check').out);
  fx.cleanup();
});

test('the region keeps the rules table and points at the index, and lists no document of either tier', () => {
  const fx = layoutFixture('index-region');
  fx.repoFx.write('.claude/knowledge/ours.md', doc('ours'));
  fx.repoFx.write('.claude/skills/house/SKILL.md', skill('house'));
  fx.sync();

  const region = fx.repoFx.region()!;
  assert.ok(region.includes(`## Read on demand\n\n${pointer(INDEX)}\n`), region);
  assert.doesNotMatch(region, /## Invoke by name/);
  assert.doesNotMatch(region, /storage|finder|ours|house/, 'no knowledge or skill row is left in the region');
  assert.ok(region.indexOf('| `sensitive-info` |') < region.indexOf('## Read on demand'));
  assert.ok(region.indexOf('## Read on demand') < region.indexOf('<!-- daoris: core/core/rules/'));
  fx.cleanup();
});

/** D128 §0.3's fixture: the pilot's 169 knowledge documents, 166 without frontmatter, and 18 skills. */
test('169 knowledge documents and 18 skills leave the region\'s bytes unchanged', () => {
  const fx = layoutFixture('index-169');
  fx.sync();
  const before = fx.repoFx.region()!;

  for (let at = 0; at < 169; at += 1) {
    const name = `topic-${String(at).padStart(3, '0')}`;
    fx.repoFx.write(`.claude/knowledge/${name}.md`, at < 3 ? doc(name) : `# Topic ${at}\n\nNotes on it.\n`);
  }
  for (let at = 0; at < 18; at += 1) fx.repoFx.write(`.claude/skills/house-${at}/SKILL.md`, skill(`house-${at}`));
  fx.sync();

  assert.equal(Buffer.byteLength(fx.repoFx.region()!, 'utf8'), Buffer.byteLength(before, 'utf8'));
  assert.equal(fx.repoFx.region(), before);
  const index = fx.repoFx.read(INDEX);
  assert.equal(index.match(/^\| `\.claude\/knowledge\//gm)!.length, 170);
  assert.equal(index.match(/^\| `\.claude\/skills\//gm)!.length, 19);
  assert.equal(fx.cli('check').code, 0, fx.cli('check').out);
  fx.cleanup();
});

test('index cell: not in the lock, the same as would be written — adopted silently', () => {
  const fx = layoutFixture('index-adopt');
  fx.sync();
  // A lock written before the index, or by a build that does not know it, beside the file as written.
  const { index: _dropped, ...older } = fx.lock();
  writeLock(fx.repoFx.root, older);

  const plan = fx.plan();
  assert.equal(plan.index.collision, false);
  assert.equal(plan.index.state, 'unchanged');
  assert.equal(fx.sync().index, INDEX);
  fx.cleanup();
});

test('index cell: not in the lock, anything else — the repository\'s own file: refused, naming it; --force names what it overwrote', () => {
  const fx = layoutFixture('index-collide');
  fx.repoFx.write(INDEX, '# Our own index\n');

  const dry = fx.cli('sync', '--dry-run');
  assert.equal(dry.code, 1, dry.out);
  assert.match(dry.out, /COLLIDES\s+\.claude\/INDEX\.md \(this repo's own\)/);

  const error = captureError(() => fx.sync());
  assert.ok(error instanceof DaorisError);
  assert.equal(error.exitCode, 1);
  assert.match(error.message, /\.claude\/INDEX\.md/);
  assert.equal(fx.repoFx.read(INDEX), '# Our own index\n');
  assert.equal(fx.repoFx.exists('daoris.lock'), false, 'refused before anything was written');

  const forced = fx.cli('sync', '--force');
  assert.equal(forced.code, 0, forced.out);
  assert.match(forced.out, /overwrote \.claude\/INDEX\.md \(this repo's own file\)/);
  assert.ok(fx.repoFx.read(INDEX).startsWith('# Index\n'));
  fx.cleanup();
});

test('index cell: in the lock, anything — rewritten, since it is generated; check names it stale first', () => {
  const fx = layoutFixture('index-rewrite');
  fx.sync();
  fx.repoFx.write(INDEX, `${fx.repoFx.read(INDEX)}\nA hand edit.\n`);

  const stale = fx.cli('check');
  assert.equal(stale.code, 1, stale.out);
  assert.match(stale.out, /index\s+\.claude\/INDEX\.md is out of date — run 'daoris sync'/);
  assert.doesNotMatch(stale.out, /roster/, 'the region did not move');
  assert.equal(fx.plan().index.collision, false);

  fx.sync();
  assert.doesNotMatch(fx.repoFx.read(INDEX), /A hand edit/);
  assert.equal(fx.cli('check').code, 0);

  rmSync(join(fx.repoFx.root, INDEX));
  const absent = fx.cli('check');
  assert.equal(absent.code, 1, absent.out);
  assert.match(absent.out, /index\s+\.claude\/INDEX\.md is absent — run 'daoris sync'/);
  fx.sync();
  assert.ok(fx.repoFx.exists(INDEX));
  fx.cleanup();
});

test('a document added and never synced: check names the index, and not the region', () => {
  const fx = layoutFixture('index-behind');
  fx.sync();
  fx.repoFx.write('.claude/knowledge/ours.md', doc('ours'));

  const { code, out } = fx.cli('check');

  assert.equal(code, 1, out);
  assert.match(out, /index\s+\.claude\/INDEX\.md is out of date/);
  assert.doesNotMatch(out, /roster/);
  fx.cleanup();
});

test('a lock written before the index: check says it is absent until sync writes it', () => {
  const fx = layoutFixture('index-older-lock');
  fx.sync();
  const { index: _dropped, ...older } = fx.lock();
  writeLock(fx.repoFx.root, older);
  rmSync(join(fx.repoFx.root, INDEX));

  const absent = fx.cli('check');
  assert.equal(absent.code, 1, absent.out);
  assert.match(absent.out, /\.claude\/INDEX\.md is absent/);
  assert.equal(fx.sync().index, INDEX);
  assert.equal(fx.cli('check').code, 0);
  fx.cleanup();
});

/** D128 §2.7: every adopter meets this at its next sync, and `check` says so until then. */
test('a repository synced before the index: check names both halves, and one sync migrates it', () => {
  const fx = layoutFixture('index-migrate');
  fx.sync();
  // The region as the previous build wrote it: the tables where the pointer is, no index, no lock field.
  const older = fx.repoFx.read('AGENTS.md').replace(`${pointer(INDEX)}\n`, [
    '| Knowledge | Applies when | Enforces |', '|---|---|---|', '| [storage](.claude/knowledge/storage.md) | w | e |', '',
    '## Invoke by name', '', '| Skill | Use when |', '|---|---|', '| [finder](.claude/skills/finder) | Use when finder is wanted. |', '',
  ].join('\n'));
  assert.notEqual(older, fx.repoFx.read('AGENTS.md'));
  fx.repoFx.write('AGENTS.md', older);
  rmSync(join(fx.repoFx.root, INDEX));
  const { index: _dropped, ...lock } = fx.lock();
  writeLock(fx.repoFx.root, lock);

  const stale = fx.cli('check');
  assert.equal(stale.code, 1, stale.out);
  assert.match(stale.out, /index\s+\.claude\/INDEX\.md is absent — run 'daoris sync'/);
  assert.match(stale.out, /roster\s+the doctrine region's pointer or rooms are out of date — run 'daoris sync'/);
  assert.doesNotMatch(stale.out, /drifted/, 'no rule moved');

  const synced = fx.cli('sync');
  assert.equal(synced.code, 0, synced.out);
  assert.doesNotMatch(fx.repoFx.region()!, /## Invoke by name|\[storage\]/);
  assert.ok(fx.repoFx.exists(INDEX));
  assert.equal(fx.cli('check').code, 0);
  fx.cleanup();
});

test('index cell: in the lock at the old root after a move — written at the new root, the old deleted', () => {
  const fx = layoutFixture('index-move');
  fx.sync();
  fx.flip('agents');

  const dry = fx.cli('sync', '--dry-run');
  assert.match(dry.out, /moved\s+\.claude\/INDEX\.md -> \.agents\/INDEX\.md/);
  assert.ok(fx.repoFx.exists(INDEX), 'a dry run writes nothing');

  const lock = fx.sync();

  assert.equal(fx.repoFx.exists(INDEX), false);
  assert.equal(lock.index, '.agents/INDEX.md');
  const index = fx.repoFx.read('.agents/INDEX.md');
  assert.match(index, /\| `\.agents\/knowledge\/storage\.md` \|/);
  assert.match(index, /\| `\.agents\/skills\/finder\/SKILL\.md` \|/);
  // The mirror is not a source: the index lists each skill once, where it is edited.
  assert.doesNotMatch(index, /\.claude\/skills/);
  const region = fx.repoFx.region()!;
  assert.ok(region.includes(pointer('.agents/INDEX.md')), region);
  assert.match(region, /Skills live in `\.agents\/skills\/`; `\.claude\/skills\/` mirrors them for the agent that reads only there — edit the source\./);
  assert.equal(fx.cli('check').code, 0, fx.cli('check').out);
  fx.cleanup();
});

test('index cell: a move onto an INDEX.md of the repository\'s own at the new root — a collision', () => {
  const fx = layoutFixture('index-move-collide');
  fx.sync();
  fx.flip('agents');
  fx.repoFx.write('.agents/INDEX.md', '# Ours\n');

  const error = captureError(() => fx.sync());

  assert.ok(error instanceof DaorisError);
  assert.match(error.message, /\.agents\/INDEX\.md/);
  assert.equal(fx.repoFx.read('.agents/INDEX.md'), '# Ours\n');
  assert.ok(fx.repoFx.exists(INDEX), 'the old index stays until the move can be made');
  fx.cleanup();
});

test('index cell: a link held as text — refused, never written through, even with --force', () => {
  const fx = layoutFixture('index-text');
  fx.repoFx.write(INDEX, '../.agents/INDEX.md');

  const error = captureError(() => fx.sync());

  assert.ok(error instanceof DaorisError);
  assert.equal(error.exitCode, 1);
  assert.match(error.message, /\.claude\/INDEX\.md/);
  assert.match(error.message, TEXT);
  assert.ok(captureError(() => fx.sync(true)) instanceof DaorisError);
  assert.equal(fx.repoFx.read(INDEX), '../.agents/INDEX.md');
  fx.cleanup();
});

test('check fails on an index that has become a link held as text', () => {
  const fx = layoutFixture('index-text-check');
  fx.sync();
  fx.repoFx.write(INDEX, '../.agents/INDEX.md');

  const { code, out } = fx.cli('check');

  assert.equal(code, 1, out);
  assert.match(out, /LINK\s+\.claude\/INDEX\.md/);
  fx.cleanup();
});

/** D18 for the lock's new field: the lock is generated, the file nobody reads closely. */
test('a lock naming its index anywhere but the target\'s INDEX.md is refused, and nothing is touched', () => {
  for (const crafted of ['.claude/knowledge/storage.md', '../outside/INDEX.md']) {
    const fx = layoutFixture('index-crafted');
    fx.sync();
    writeLock(fx.repoFx.root, { ...fx.lock(), index: crafted });

    const error = captureError(() => fx.sync());

    assert.ok(error instanceof DaorisError, crafted);
    assert.match(error.message, /daoris\.lock/);
    assert.ok(fx.repoFx.exists('.claude/knowledge/storage.md'), crafted);
    fx.cleanup();
  }
});
