import type { CliCommand } from '../types.ts';
import { commandHarness } from '../toolchain.ts';
import { releaseFetcher } from '../service.ts';

export const command: CliCommand = {
  name: 'agent',
  kind: 'management',
  // The tools a session runs are agents to a person; `harness` stays the code's word (AGT1).
  formerly: ['harness'],
  usage: [
    "  agent [verb]         this machine's agents — Claude Code, Codex, dsh — and the",
    "                       accounts they run as. A sign-in stays the tool's:",
    '                         list                      installed? version? accounts?',
    '                         install <agent>           its OWN installer, never auto',
    '                         update <agent> [--workspace W]',
    '                                                   pinned: the pin moves to the',
    '                                                   newest release, resolved to',
    '                                                   one exact version; unpinned:',
    "                                                   the agent's own updater",
    '                         login <agent> [--profile P] [--join W] [--join-machine]',
    '                                                   its own login flow, run INTO',
    "                                                   an account that is here, by",
    '                                                   its id or name, else the',
    '                                                   default; never a new folder',
    '                         login <agent> --new [--name N] [--join W] [--join-machine]',
    '                                                   sign in to a new account:',
    '                                                   kept only if it finished;',
    '                                                   offers who signed in as its',
    '                                                   name; --join puts it in a',
    "                                                   workspace's list, and the end",
    '                                                   says which lists hold it',
    '                         key <agent>               an account that is an API key,',
    '                                                   read from stdin; Daoris keeps it',
    '                         profile list|add|remove <agent> <profile>',
    '                                                   remove deletes the account,',
    '                                                   sign-in and all',
    '                         profile default <agent> <profile>|--clear [--workspace W]',
    "                                                   --clear names none again: the",
    "                                                   agent's own home, or for a",
    "                                                   workspace the machine's default",
    '                         profile order <agent> <profile>…|--clear [--workspace W]',
    '                                                   the accounts rotation may use,',
    '                                                   in order; one not listed never',
    '                                                   rotates, into or away',
    '                         profile use <agent> [goal|order] [--keep <account>|--no-keep]',
    '                               [--early on|off] [--near <percent>] [--workspace W]',
    '                                                   how a list is used: goal, make',
    '                                                   the most of its accounts, or',
    '                                                   order, one by one in order;',
    '                                                   one kept for conversations;',
    '                                                   switch before a limit. No flag',
    '                                                   prints them; --clear returns',
    "                                                   to today's defaults",
    '                         profile ready <agent> <profile>|--own',
    "                                                   end an account's cool-off now:",
    "                                                   --own is the tool's own sign-in",
    '                         profile rename <agent> <account> <name>',
    "                                                   an account's name, yours: its",
    '                                                   id stays, so every list,',
    '                                                   default and record keeps it;',
    '                                                   its own id gives it none',
    '                         profile join <agent> <account> [<workspace>…] [--machine]',
    "                                                   put an account in a workspace's",
    "                                                   list, or this machine's",
    '                         pin <agent> <version> [--workspace W]',
    '                                                   install that version somewhere',
    '                                                   Daoris owns, and run it. Claude',
    '                                                   Code and Codex come from their',
    "                                                   makers' own channels, verified",
    '                         unpin <agent> [--workspace W]',
    '                                                   back to whatever is on PATH',
    '                         trust <agent> <folder> [--profile P] --yes',
    '                                                   what the agent asks the first',
    '                                                   time it runs in a folder, granted',
    '                                                   in its own file; without --yes,',
    '                                                   the question and nothing written',
    '                         settings <agent> [--account A] [model M] [effort E [--for M]]',
    "                                                   an account's own model and",
    "                                                   effort, in the tool's own",
    '                                                   settings file; unset clears,',
    '                                                   and given neither, it prints them',
    '                         rules [allow|ask|deny|remove <rule>]',
    '                               [--workspace W | --repository R]',
    '                                                   what a session Daoris starts may',
    '                                                   do; rules default <id> on|off',
    '                         rules proposals|accept|decline <id>',
    '                                                   what agents asked to change',
  ],
  options: [
    '  --profile <name>     which account to act on (agent login) — a named,',
    '                       isolated configuration home for that agent; any',
    '                       verb takes an account by its id or its name',
    '  --name <name>        a new account\'s name, as it is made (agent login --new)',
    '  --join <workspace>   a list a sign-in puts its account in, at its end;',
    '                       repeated or comma-separated. --join-machine is this',
    "                       machine's list (agent login)",
  ],
  // `pin` and a pinned `update` fetch a maker's release (AGT2b, USE1a) through the one module that may
  // reach a network, handed in here so the toolchain never holds a socket of its own.
  run: (args) => commandHarness(args, releaseFetcher()),
};
