import type { CliCommand } from '../types.ts';
import { commandDriver } from '../driverconfig.ts';
import { registryCheckouts, sessionRecords } from '../service.ts';

export const command: CliCommand = {
  name: 'driver',
  kind: 'management',
  usage: [
    '  driver [verb]        what this machine drives ($DAORIS_HOME/driver.json):',
    '                         list                      adapter, cap, what is opted in',
    '                         drive|undrive <repo>      opt a repository in, or out',
    '                         hold|resume <repo>        hold one, or resume it',
    '                         trees <repo> on|off       sessions there open their own',
    '                                                   worktree (D51) — your dirty',
    '                                                   root stops holding the driver',
    '                         line <repo> <branch>|--clear',
    '                                                   the branch its work grows from',
    '                                                   and lands on (--workspace <name>',
    '                                                   for each repo there with none)',
    '                         landing <repo> merge|branch <pattern>|--clear',
    '                                                   how accepted work lands: into',
    '                                                   the line, or on a branch you',
    '                                                   push (--workspace <name> too;',
    '                                                   --tidy removes the tree after;',
    '                                                   --plugin <id> on a branch: an',
    '                                                   installed plugin pushes it and',
    '                                                   opens the pull request;',
    '                                                   --auto-accept on a branch: a',
    '                                                   quest\'s done lands it with no',
    '                                                   press, and the plugin pushes)',
    '                         across <repo> read on|off|--clear',
    '                                                   whether agents outside it read',
    '                                                   its checkout; on by default',
    '                                                   (--workspace <name> too)',
    '                         across <repo> write-to <other> [--clear]',
    '                                                   let its sessions also write',
    '                                                   into <other>: your say-so',
    '                         standing <repo> "…"|--clear',
    '                                                   an answer handed to every',
    '                                                   session there: which writes',
    '                                                   are allowed, where to test;',
    '                                                   kept here, never in the repo',
    '                         language <repo> en|zh|--clear',
    '                                                   the language its sessions write',
    '                                                   to you in (--workspace <name>',
    '                                                   for each repo there with none);',
    '                                                   the window\'s is Appearance\'s',
    '                         review <repo> <environment> --kind local|deployed',
    '                                --procedure <path> [--address <url>] [--run "…"]',
    '                                                   where its work is shown to you',
    '                                                   before it lands (--workspace',
    '                                                   <name> too; --required: work',
    '                                                   is to wait for your look);',
    '                                                   none, --drop <environment>,',
    '                                                   --not-required, or --clear;',
    '                                                   declared only: nothing reads',
    '                                                   it yet',
    '                         opinion <repo> --reviewers <adapter,adapter>',
    '                                [--on landing,steps] [--minutes <n>]',
    '                                                   which other agent reads its',
    '                                                   work before it lands, in a copy',
    '                                                   of its own (--workspace <name>',
    '                                                   too; --required: work waits if',
    '                                                   none can; --verify: it may run',
    '                                                   what is declared safe;',
    '                                                   --no-recheck); none, or --clear;',
    '                                                   declared only: nothing reads',
    '                                                   it yet',
    '                         notify on|off           say so when a session parks,',
    '                                                   or ends without you asking',
    '                         intake <adapter>|off      answer an ask the declarations',
    '                                                   do not settle with a session',
    '                                                   on that harness, a login each',
    '                         helper <adapter>|off      the agent Ask Daoris runs on;',
    '                                                   it proposes, and you apply',
    '                         strikes <n>               park a quest after n failed',
    '                                                   sessions; 0 never parks',
    '                         retry <quest> [--at <n>]  start a parked quest again,',
    "                                                   counted from this machine's",
    '                                                   records, or from n failures',
    '                         retry <quest> --session <id>',
    '                                                   release a quest your stop',
    '                                                   of that session holds',
    '                         timeout <minutes>         how long one session may run',
    '                         cooloff <minutes>         how long an account cools when',
    '                                                   its agent names no time for',
    '                                                   its limit; 60 by default',
    '                         cap <n> · adapter <name>',
  ],
  // `retry` without `--at` counts the quest's failures from this machine's records (RETRY1b), and `review` looks for a
  // procedure in the registry's checkouts (REVIEWENV1a), through the one module that may reach a network, handed in here so
  // `driverconfig.ts` never holds a socket of its own.
  run: (args) => commandDriver(args, () => sessionRecords(), () => registryCheckouts()),
};
