import type { CliCommand } from '../types.ts';
import { commandDriver } from '../driverconfig.ts';

export const command: CliCommand = {
  name: 'driver',
  kind: 'management',
  usage: [
    '  driver [verb]        what this machine drives ($DAORIS_HOME/driver.json):',
    '                         list                      adapter, cap, what is opted in',
    '                         drive|undrive <repo>      opt a repository in, or out',
    '                         hold|resume <repo>        pause one, or release it',
    '                         trees <repo> on|off       sessions there open their own',
    '                                                   worktree (D51) — your dirty',
    '                                                   root stops holding the driver',
    '                         line <repo> <branch>|--clear',
    '                                                   the branch its work grows from',
    '                                                   and lands on (--workspace <name>',
    '                                                   for each repo there with none)',
    '                         landing <repo> merge|branch <pattern>|--clear',
    '                                                   how accepted work lands: into',
    '                                                   the line, or on a branch you',
    '                                                   push (--workspace <name> too;',
    '                                                   --tidy removes the tree after;',
    '                                                   --plugin <id> on a branch: an',
    '                                                   installed plugin pushes it and',
    '                                                   opens the pull request)',
    '                         across <repo> read on|off|--clear',
    '                                                   whether agents outside it read',
    '                                                   its checkout; on by default',
    '                                                   (--workspace <name> too)',
    '                         across <repo> write-to <other> [--clear]',
    '                                                   let its sessions also write',
    '                                                   into <other>: your say-so',
    '                         notify on|off           say so when a session parks,',
    '                                                   or ends without you asking',
    '                         intake <adapter>|off      answer an ask the declarations',
    '                                                   do not settle with a session',
    '                                                   on that harness, a login each',
    '                         helper <adapter>|off      the agent Ask Daoris runs on;',
    '                                                   it proposes, and you apply',
    '                         strikes <n>               park a quest after n failed',
    '                                                   sessions; 0 never parks',
    '                         retry <quest> [--at <n>]  start a parked quest again',
    '                         retry <quest> --session <id>',
    '                                                   release a quest your stop',
    '                                                   of that session holds',
    '                         timeout <minutes>         how long one session may run',
    '                         cooloff <minutes>         how long an account cools when',
    '                                                   its agent names no time for',
    '                                                   its limit; 60 by default',
    '                         cap <n> · adapter <name>',
  ],
  run: commandDriver,
};
