#!/usr/bin/env node
/**
 * The orientation index: where things are in this repository, generated from the code (ORIENT1a) and the
 * decisions (ORIENT1b), so a session starts from a lookup rather than a search.
 *
 * ## Why
 *
 * Measured on ten branches of 2026-10-04 (ORIENT1): 60 to 100 tool calls and 370 to 600 KB read before the
 * first edit, about a third of each branch; 278 shell greps and 117 shell dumps between them; decision files
 * read whole 21 times; files of 80 to 120 KB read whole. The code map (MAP3c) names projects and nothing in
 * them. This names what those sessions searched for, each with the file and line to open: the bridge routes
 * and what answers them, the terminal verbs, the catalogue areas, the test fixtures, an outline of every
 * large file, and every decision's notes.
 *
 * ## What it writes
 *
 * `docs/index/`, every file generated and none edited by hand, as `docs/code-map.json` is (MAP3c):
 * `README.md` (the indexes kept by hand first, then what each generated file answers, and every large file),
 * `routes.md`, `verbs.md`, `catalogues.md`, `fixtures.md`, `decisions.md`, and `outlines/<path>.md` for each file
 * over `LARGE`. The README's order is the canon's `templates/index.md` (ORIENT2a2): an index kept by hand is named,
 * never restated.
 *
 * By kind, not by lane: a lookup starts from what is sought (a route, a verb, a key, a fixture), and the
 * route table joins two lanes, the page's call and the module's handler. An outline is a file of its own,
 * because one large file's outline can fill a page and the driver lane alone holds two dozen large files.
 *
 * ## The check, and the merge
 *
 * `--check` builds the index in memory and fails, naming each file, when `docs/index/` is not what the tree
 * says. A stale index is a fact, so it gates (D54); it is declared in `daoris.gates.json` and runs at every
 * merge. Line numbers move with nearly every change, so `tools/merge-branch.mjs` writes the index into each
 * merge before its gates, and a conflict in it is resolved by writing it again, never by hand.
 *
 * The files read are the ones `git add -A` would stage, so the index speaks for the tree as it would be
 * committed. Text is read with LF endings, sizes too, so a CRLF checkout writes the same index as the
 * release runner. Paths sort by code unit, never by locale.
 *
 *   node tools/orient-index.mjs            write docs/index/
 *   node tools/orient-index.mjs --check    exit 1 naming each stale file
 *   [--root <dir>]                         another work tree's top (the tests' fixtures)
 *
 * Exit codes: 0 written or fresh · 1 stale · 2 a tool error (usage, not a work tree's top).
 */
import { spawnSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, realpathSync, rmdirSync, rmSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { byNumber, declaredDecisions, fenced, isNoteLabel } from './doc-duplicates.mjs';
import { isMain, writeAtomic } from './fsx.mjs';
import { LANES_FILE, laneMatcher, readLanes } from './merge-branch.mjs';

export const INDEX = 'docs/index';
/** A file over this many bytes (LF endings) gets an outline: past it, reading the file whole is the cost measured. */
export const LARGE = 40 * 1024;
const GENERATED = 'Generated by `node tools/orient-index.mjs` (ORIENT1); never edit by hand.';

const BRIDGE = 'src/Daoris.Web/src/bridge/';
const WEB_SRC = 'src/Daoris.Web/src/';
const SHELL = 'src/Daoris.Web/src/shell.ts';
const MODULES = 'src/Daoris.Desktop/Daoris.Desktop.Modules/';
const HTTP_HOST = 'src/Daoris.Service/Daoris.Service.Http/Program.cs';
const CLI_TABLE = 'src/Daoris.Cli/src/cli.ts';
const DESKTOP = 'src/Daoris.Desktop/';
const DRIVER_HOST = 'src/Daoris.Desktop/Daoris.Desktop.Driver.Host/Program.cs';
const DRIVER_COMMAND = 'src/Daoris.Desktop/Daoris.Desktop.Driver/DriverCommand.cs';
const DRIVER_CODE = ['src/Daoris.Desktop/Daoris.Desktop.Driver.Host/', 'src/Daoris.Desktop/Daoris.Desktop.Driver/'];
const DEVKIT = 'src/Daoris.Devkit/Daoris.Devkit.Cli/Program.cs';
const DESKTOP_TOOL = 'tools/desktop.mjs';
const PACKAGES = ['package.json', 'src/Daoris.Web/package.json'];
const LOCALES = 'src/Daoris.Web/src/locales/';
const GLOSSARY = 'src/Daoris.Web/src/locales/glossary.json';

const compare = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
const kb = (bytes) => Math.max(1, Math.round(bytes / 1024));

/** `text` cut at a word before `max` characters, with an ellipsis, so a row stays one line. */
function truncate(text, max) {
  const flat = text.replace(/\s+/g, ' ').trim();
  if (flat.length <= max) return flat;
  const cut = flat.slice(0, max);
  const space = cut.lastIndexOf(' ');
  return `${(space > max / 2 ? cut.slice(0, space) : cut).replace(/[\s,;:]+$/, '')}…`;
}

/** The 1-based line `offset` falls on. */
function lineAt(text, offset) {
  let line = 1;
  for (let at = text.indexOf('\n'); at >= 0 && at < offset; at = text.indexOf('\n', at + 1)) line += 1;
  return line;
}

const indentOf = (line) => {
  let width = 0;
  for (const c of line) {
    if (c === ' ') width += 1;
    else if (c === '\t') width += 4;
    else break;
  }
  return width;
};

const isComment = (trimmed) => trimmed.startsWith('//') || trimmed.startsWith('/*') || trimmed.startsWith('*');

// ---------------------------------------------------------------------------------------------------
// The files: what `git add -A` would stage, read with LF endings

const samePath = (a, b) => {
  const real = (path) => realpathSync(path).replace(/\\/g, '/').replace(/\/+$/, '');
  return process.platform === 'win32' ? real(a).toLowerCase() === real(b).toLowerCase() : real(a) === real(b);
};

/**
 * The files of the work tree at `root`, as `/`-separated paths sorted by code unit: tracked and untracked, without
 * the ignored, the way `git add -A` would stage them. `root` must be the tree's top: git walks up from a folder that
 * is not a repository and would answer for the one above it.
 */
export function listFiles(root) {
  const top = spawnSync('git', ['rev-parse', '--show-toplevel'], { cwd: root, encoding: 'utf8' });
  if (top.status !== 0 || !samePath(top.stdout.trim(), root)) throw new Error(`${root} is not the top of a git work tree`);
  const listed = spawnSync('git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard'], {
    cwd: root, encoding: 'utf8', maxBuffer: 256 * 1024 * 1024,
  });
  if (listed.status !== 0) throw new Error(`git ls-files failed: ${listed.stderr.trim()}`);
  return [...new Set(listed.stdout.split('\0').filter(Boolean))]
    .filter((path) => {
      try {
        return statSync(join(root, path)).isFile();
      } catch {
        return false;
      }
    })
    .sort(compare);
}

/** One read of each file, BOM-less and with LF endings, for every section that needs it. */
function reader(root, files) {
  const cache = new Map();
  const known = new Set(files);
  const read = (path) => {
    if (!cache.has(path)) cache.set(path, readFileSync(join(root, path), 'utf8').replace(/^\uFEFF/, '').replace(/\r\n/g, '\n'));
    return cache.get(path);
  };
  return { root, files, has: (path) => known.has(path), read, lines: (path) => read(path).split('\n') };
}

// ---------------------------------------------------------------------------------------------------
// Strings and comments that span lines, so no declaration is read out of one

/**
 * C#: which lines start inside a block comment, a verbatim string or a raw string, the constructs that span lines.
 * A regular string or a character ends at its line's end at the latest, so a misread one costs that line only.
 */
function csInside(lines) {
  const inside = [];
  let state = null;
  for (const line of lines) {
    inside.push(state !== null);
    let i = 0;
    while (i < line.length) {
      if (state?.kind === 'block') {
        const end = line.indexOf('*/', i);
        if (end < 0) break;
        i = end + 2;
        state = null;
        continue;
      }
      if (state?.kind === 'verbatim') {
        const quote = line.indexOf('"', i);
        if (quote < 0) break;
        if (line[quote + 1] === '"') {
          i = quote + 2;
          continue;
        }
        i = quote + 1;
        state = null;
        continue;
      }
      if (state?.kind === 'raw') {
        const close = line.indexOf(state.run, i);
        if (close < 0) break;
        i = close + state.run.length;
        state = null;
        continue;
      }
      const c = line[i];
      if (c === '/' && line[i + 1] === '/') break;
      if (c === '/' && line[i + 1] === '*') {
        state = { kind: 'block' };
        i += 2;
        continue;
      }
      if (c === "'") {
        const char = /'(?:\\.|[^'\\])+'/y;
        char.lastIndex = i;
        i = char.test(line) ? char.lastIndex : i + 1;
        continue;
      }
      if (c === '"' || ((c === '$' || c === '@') && /^[$@]*"/.test(line.slice(i, i + 8)))) {
        let j = i;
        let verbatim = false;
        while (line[j] === '$' || line[j] === '@') {
          if (line[j] === '@') verbatim = true;
          j += 1;
        }
        let q = j;
        while (line[q] === '"') q += 1;
        const quotes = q - j;
        if (quotes >= 3) {
          const run = '"'.repeat(quotes);
          const close = line.indexOf(run, q);
          if (close < 0) {
            state = { kind: 'raw', run };
            break;
          }
          i = close + quotes;
          continue;
        }
        if (quotes === 2) {
          i = q;
          continue;
        }
        if (verbatim) {
          let k = q;
          for (; k < line.length; k += 1) {
            if (line[k] !== '"') continue;
            if (line[k + 1] === '"') k += 1;
            else break;
          }
          if (k >= line.length) {
            state = { kind: 'verbatim' };
            break;
          }
          i = k + 1;
          continue;
        }
        let k = q;
        while (k < line.length && line[k] !== '"') k += line[k] === '\\' ? 2 : 1;
        i = k + 1;
        continue;
      }
      i += 1;
    }
  }
  return { inside, clean: state === null };
}

const REGEX_AFTER = new Set(['', '(', ',', '=', ':', '[', '!', '&', '|', '?', '{', '}', ';', '+', '-', '*', '%', '>', '~', '^']);
const REGEX_AFTER_WORD = new Set(['return', 'typeof', 'case', 'in', 'of', 'delete', 'void', 'throw', 'new', 'else', 'do', 'yield', 'await']);

/**
 * TypeScript and JavaScript: which lines start inside a block comment or a template literal (holes and nested
 * templates followed). A regular expression is told from a division by what stands before it, as a lexer does.
 */
function tsInside(lines) {
  const inside = [];
  const stack = [];
  for (const line of lines) {
    inside.push(stack.length > 0);
    let prev = '';
    let i = 0;
    while (i < line.length) {
      const top = stack.at(-1);
      if (top === 'block') {
        const end = line.indexOf('*/', i);
        if (end < 0) break;
        stack.pop();
        i = end + 2;
        continue;
      }
      if (top === 'template') {
        const c = line[i];
        if (c === '\\') i += 2;
        else if (c === '`') {
          stack.pop();
          prev = '`';
          i += 1;
        } else if (c === '$' && line[i + 1] === '{') {
          stack.push({ hole: 1 });
          prev = '{';
          i += 2;
        } else i += 1;
        continue;
      }
      const c = line[i];
      if (c === ' ' || c === '\t') {
        i += 1;
        continue;
      }
      if (c === '/' && line[i + 1] === '/') break;
      if (c === '/' && line[i + 1] === '*') {
        stack.push('block');
        i += 2;
        continue;
      }
      if (c === '`') {
        stack.push('template');
        i += 1;
        continue;
      }
      if (c === "'" || c === '"') {
        let k = i + 1;
        while (k < line.length && line[k] !== c) k += line[k] === '\\' ? 2 : 1;
        i = k + 1;
        prev = c;
        continue;
      }
      if (c === '/' && (REGEX_AFTER.has(prev) || REGEX_AFTER_WORD.has(prev))) {
        let k = i + 1;
        let inClass = false;
        for (; k < line.length; k += 1) {
          const d = line[k];
          if (d === '\\') k += 1;
          else if (inClass) inClass = d !== ']';
          else if (d === '[') inClass = true;
          else if (d === '/') break;
        }
        i = k + 1;
        while (i < line.length && /[a-z]/.test(line[i])) i += 1;
        prev = '/';
        continue;
      }
      if (/[A-Za-z0-9_$]/.test(c)) {
        const word = /[A-Za-z0-9_$]+/y;
        word.lastIndex = i;
        word.test(line);
        prev = line.slice(i, word.lastIndex);
        i = word.lastIndex;
        continue;
      }
      if (top && typeof top === 'object') {
        if (c === '{') top.hole += 1;
        else if (c === '}' && --top.hole === 0) {
          stack.pop();
          prev = '';
          i += 1;
          continue;
        }
      }
      // `=>` before a regular expression reads as `>`, which allows one; `<` never does (a closing JSX tag).
      prev = c === '<' ? '<' : c;
      i += 1;
    }
  }
  return { inside, clean: stack.length === 0 };
}

/**
 * Which lines start inside a construct that spans lines, and whether the scan ended outside one. A scan that did not
 * end clean misread something, so its answer is not used: the outline then reads every line as code.
 */
export function continued(lines, language) {
  return language === 'cs' ? csInside(lines) : tsInside(lines);
}

const trusted = (lines, language) => {
  const scan = continued(lines, language);
  return scan.clean ? scan.inside : lines.map(() => false);
};

// ---------------------------------------------------------------------------------------------------
// Outlines

/** A line that only closes: `}`, `});`, `]`, `} as const;`. Any other line that starts with a closer goes on. */
const PURE_CLOSER = /^[}\])][}\])]*(?:\s*(?:as const|satisfies\s+[^;]+))?[;,)]*\s*$/;

/**
 * The last line of a declaration that starts at `start` with `indent`: its own closing line at that indent, or the
 * last line before the next thing at that indent or shallower. Comments and blank lines in between are left to what
 * follows, so a range never ends on the next declaration's doc comment.
 */
function endOf(lines, inside, start, indent) {
  let last = start;
  for (let i = start + 1; i < lines.length; i += 1) {
    if (inside[i]) {
      last = i;
      continue;
    }
    const trimmed = lines[i].trim();
    if (!trimmed || isComment(trimmed)) continue;
    const at = indentOf(lines[i]);
    if (at > indent) {
      last = i;
      continue;
    }
    if (at < indent) break;
    if (trimmed === '{') {
      last = i;
      continue;
    }
    if (PURE_CLOSER.test(trimmed)) return i;
    if (/^[}\])]/.test(trimmed)) {
      last = i;
      continue;
    }
    break;
  }
  return last;
}

/**
 * Depth by containment: an entry inside an earlier one's range, and deeper than it, is under it. Lines come back
 * 1-based; whatever else an entry carries is kept, for the fixtures.
 */
function nest(entries) {
  entries.sort((a, b) => a.start - b.start || b.end - a.end);
  const open = [];
  for (const entry of entries) {
    while (open.length && (open.at(-1).end < entry.start || open.at(-1).indent >= entry.indent)) open.pop();
    entry.depth = open.length;
    open.push(entry);
  }
  return entries.map((entry) => ({ ...entry, start: entry.start + 1, end: entry.end + 1 }));
}

const CS_KEYWORDS = new Set([
  'if', 'for', 'foreach', 'while', 'switch', 'catch', 'using', 'lock', 'return', 'nameof', 'typeof', 'sizeof', 'default',
  'base', 'this', 'new', 'when', 'get', 'set', 'init', 'add', 'remove', 'await', 'throw', 'yield', 'else', 'case', 'goto',
  'in', 'is', 'as', 'not', 'and', 'or', 'var', 'do', 'try', 'fixed', 'checked', 'unchecked', 'stackalloc', 'out', 'ref',
]);
const CS_TYPE = /^\s*((?:(?:public|private|protected|internal|static|sealed|abstract|partial|readonly|ref|unsafe|new|file)\s+)*)(record\s+struct|record\s+class|record|class|struct|interface|enum)\s+(@?[A-Za-z_]\w*)/;
const CS_ROUTE = /\.Map(Get|Post|Put|Delete|Patch)\(\s*"([^"]+)"/;
const ATTRIBUTES = /^\s*(?:\[(?:[^[\]]|\[[^\]]*\])*\]\s*)+/;
const CS_MODIFIER_END = /\b(?:public|private|protected|internal|static|async|override|virtual|abstract|sealed|extern|unsafe|new|partial|readonly|file|required|ref)$/;

/**
 * A C# member declared on `line`: a method, a constructor, an operator or a local function, by the name before its
 * first parenthesis. A field, a property and a statement are not one: an initialiser's `=` stands before the
 * parenthesis, and a call has no type before its name. Null when the line declares none.
 */
function csMember(line, { inType }) {
  const code = line.replace(ATTRIBUTES, '').replace(/\/\/.*$/, '');
  // The parameters' parenthesis, past a tuple type: `public (string? Value, ChoiceFrom From) ResolveFrom(`.
  let paren = -1;
  for (let k = 0; k < code.length; k += 1) {
    if (code[k] !== '(') continue;
    const before = code.slice(0, k).trim();
    if (before === '' || /[<,]$/.test(before) || CS_MODIFIER_END.test(before)) {
      for (let depth = 0; k < code.length; k += 1) {
        if (code[k] === '(') depth += 1;
        else if (code[k] === ')' && --depth === 0) break;
      }
      continue;
    }
    paren = k;
    break;
  }
  if (paren < 0) return null;
  const head = code.slice(0, paren);
  if (/=(?!>)/.test(head) || /["'$@]/.test(head)) return null;
  const named = /(operator\s*[^\s(]+|@?[A-Za-z_]\w*)\s*(?:<[^()]*>)?\s*$/.exec(head);
  if (!named) return null;
  const prefix = head.slice(0, named.index).trim();
  const name = named[1];
  // `x.Foo(` and `x?.Foo(` are calls; `object? Foo(` is a nullable return type.
  if (CS_KEYWORDS.has(name) || prefix.endsWith('.')) return null;
  const first = prefix.split(/\s+/)[0] ?? '';
  if (CS_KEYWORDS.has(first) && !['new', 'ref'].includes(first)) return null;
  // Outside a type a call can stand at any indent: a local function names a type before it, and a statement that
  // ends at its line has no body, unless it is the arrow of an expression-bodied function.
  if (!inType && (!prefix || (code.trimEnd().endsWith(';') && !code.slice(paren).includes('=>')))) return null;
  return { name: name.replace(/\s+/g, ' '), modifiers: prefix };
}

/**
 * A C# file's types, members and, in top-level statements, local functions and mapped routes, each with its lines.
 * Members are read at the indent of a type's body only, so a statement inside a method is never taken for one.
 */
export function outlineCSharp(text) {
  const lines = text.split('\n');
  const inside = trusted(lines, 'cs');
  const entries = [];
  const stack = [];
  for (let i = 0; i < lines.length; i += 1) {
    if (inside[i]) continue;
    const trimmed = lines[i].trim();
    if (!trimmed || isComment(trimmed) || trimmed.startsWith('#')) continue;
    const indent = indentOf(lines[i]);
    while (stack.length && indent <= stack.at(-1).indent) {
      if (indent === stack.at(-1).indent && /^[{}]/.test(trimmed)) break;
      stack.pop();
    }
    if (/^[{}\])]/.test(trimmed) || /^\[[^\]]*\]$/.test(trimmed)) continue;
    const container = stack.at(-1) ?? null;
    if (container) {
      container.body ??= indent;
      if (indent !== container.body) continue;
    }
    if (/^namespace\s+[\w.]+\s*$/.test(trimmed)) {
      stack.push({ indent, body: null, namespace: true });
      continue;
    }
    const type = CS_TYPE.exec(lines[i].replace(ATTRIBUTES, ''));
    if (type) {
      const kind = type[2].split(/\s+/)[0];
      entries.push({ start: i, indent, name: `${kind} ${type[3]}`, kind: 'type', modifiers: type[1].trim(), type: type[3] });
      stack.push({ indent, body: null });
      continue;
    }
    if (!container || container.namespace) {
      const route = CS_ROUTE.exec(lines[i]);
      if (route) {
        entries.push({ start: i, indent, name: `${route[1].toUpperCase()} ${route[2]}`, kind: 'route' });
        continue;
      }
    }
    const member = csMember(lines[i], { inType: container !== null && !container.namespace });
    if (member) entries.push({ start: i, indent, name: `${member.name}()`, kind: 'member', modifiers: member.modifiers, member: member.name });
  }
  for (const entry of entries) entry.end = endOf(lines, inside, entry.start, entry.indent);
  return nest(entries);
}

const TS_TOP = [
  [/^export\s+default\s+(?:async\s+)?function\s*\*?\s*([A-Za-z_$][\w$]*)?/, 'function'],
  [/^(?:export\s+)?(?:async\s+)?function\s*\*?\s*([A-Za-z_$][\w$]*)/, 'function'],
  [/^(?:export\s+)?(?:default\s+)?(?:abstract\s+)?class\s+([A-Za-z_$][\w$]*)/, 'class'],
  [/^export\s+(?:declare\s+)?(?:const\s+)?enum\s+([A-Za-z_$][\w$]*)/, 'enum'],
  [/^export\s+(?:declare\s+)?interface\s+([A-Za-z_$][\w$]*)/, 'interface'],
  [/^export\s+(?:declare\s+)?type\s+([A-Za-z_$][\w$]*)/, 'type'],
  [/^export\s+(?:const|let|var)\s+([A-Za-z_$][\w$]*)/, 'const'],
  [/^(?:const|let)\s+([A-Za-z_$][\w$]*)\s*(?::[^=]+)?=\s*(?:async\s+)?(?:function\b|\(|<|[A-Za-z_$][\w$]*\s*=>|memo\(|forwardRef\()/, 'const'],
];
const TS_MEMBER = /^\s+(?:(?:static|async|get|set|private|public|protected|readonly|override|abstract)\s+)*(#?[A-Za-z_$][\w$]*)\s*(?:<[^()]*>)?\s*\(/;
const TS_KEYWORDS = new Set(['if', 'for', 'while', 'switch', 'catch', 'return', 'function', 'await', 'typeof', 'new', 'super', 'throw']);
const TEST_BLOCK = /^\s*(describe|test|it)(?:\.(?:only|skip|todo|concurrent|each\([^)]*\)))*\s*\(\s*(['"`])((?:\\.|(?!\2).)*)\2/;
const SECTION = /^\s*section\(\s*(['"`])((?:\\.|(?!\1).)*)\1/;
const isTestFile = (path) => /\.(test|spec)\.[cm]?[jt]sx?$/.test(path);
/**
 * Whether a `const x = (…` declares a function: its parenthesis closes on an arrow or a return type, or stays open past
 * the line (parameters that wrap). `(a ?? b).reduce(…)` is an expression.
 */
function declaresFunction(line) {
  const m = /=\s*(?:async\s+)?(?:<[^=]*?>\s*)?\(/.exec(line);
  if (!m) return true;
  let depth = 0;
  for (let k = m.index + m[0].length - 1; k < line.length; k += 1) {
    if (line[k] === '(') depth += 1;
    else if (line[k] === ')' && --depth === 0) return /^\s*(?:=>|:)/.test(line.slice(k + 1));
  }
  return true;
}

/** A function this many lines long or more gets its body outlined too. */
const LONG_BODY = 150;
const BODY_FUNCTION = /^\s+(const|let|function)\s+([A-Za-z_$][\w$]*)\s*(?:(?::[^=]+)?=\s*(?:async\s+)?(?:\(|function\b|[A-Za-z_$][\w$]*\s*=>|useCallback\(|useMemo\()|\()/;
const BODY_EFFECT = /^\s+(useEffect|useLayoutEffect)\(/;
const BODY_RETURN = /^\s+return\s*(?:\(\s*)?(?:<.*)?$/;

/**
 * A script's top-level declarations, a class's members, a test file's groups and cases, and a tool's phases
 * (`section('…')`), each with its lines. `exported` is kept for the fixtures.
 */
export function outlineScript(text, path) {
  const lines = text.split('\n');
  const inside = trusted(lines, 'ts');
  const testFile = isTestFile(path);
  const entries = [];
  const sections = [];
  let cls = null;
  for (let i = 0; i < lines.length; i += 1) {
    if (inside[i]) continue;
    const line = lines[i];
    const trimmed = line.trim();
    if (!trimmed || isComment(trimmed)) continue;
    const indent = indentOf(line);
    if (indent === 0) {
      cls = null;
      for (const [pattern, kind] of TS_TOP) {
        const m = pattern.exec(line);
        if (!m || (kind === 'const' && !line.startsWith('export') && !declaresFunction(line))) continue;
        entries.push({ start: i, indent, name: `${kind} ${m[1] ?? 'default'}`, exported: line.startsWith('export'), id: m[1] ?? 'default' });
        if (kind === 'class') cls = { body: null };
        break;
      }
    } else if (cls && !/^[}\])]/.test(trimmed)) {
      cls.body ??= indent;
      const m = indent === cls.body ? TS_MEMBER.exec(line) : null;
      if (m && !TS_KEYWORDS.has(m[1])) entries.push({ start: i, indent, name: `${m[1]}()` });
    }
    if (testFile) {
      const m = TEST_BLOCK.exec(line);
      if (m) entries.push({ start: i, indent, name: `${m[1]} '${truncate(m[3], 64)}'` });
    } else {
      const m = SECTION.exec(line);
      if (m) sections.push({ start: i, indent: indent + 1, name: `§ ${truncate(m[2], 80)}` });
    }
  }
  for (const entry of entries) entry.end = endOf(lines, inside, entry.start, entry.indent);
  // A long function (a page's component, a tool's main) is outlined inside too: its own functions, effects and return.
  for (const entry of entries.filter((top) => top.indent === 0 && /^(function|const) /.test(top.name) && top.end - top.start >= LONG_BODY)) {
    let body = null;
    for (let i = entry.start + 1; i < entry.end; i += 1) {
      const trimmed = lines[i].trim();
      if (inside[i] || !trimmed || isComment(trimmed)) continue;
      body ??= indentOf(lines[i]);
      if (indentOf(lines[i]) !== body) continue;
      const m = BODY_FUNCTION.exec(lines[i]);
      const name = m && declaresFunction(lines[i]) ? `${m[1]} ${m[2]}` : BODY_EFFECT.exec(lines[i])?.[1] ?? (BODY_RETURN.test(lines[i]) ? 'return' : null);
      if (name) entries.push({ start: i, indent: body, name, end: endOf(lines, inside, i, body) });
    }
  }
  // A phase runs to the next phase, or to the end of the declaration it is written in.
  sections.forEach((section, k) => {
    const within = entries.filter((entry) => entry.start < section.start && entry.end >= section.start).map((entry) => entry.end);
    let end = Math.min(k + 1 < sections.length ? sections[k + 1].start - 1 : lines.length - 1, ...within);
    while (end > section.start && !lines[end].trim()) end -= 1;
    section.end = end;
  });
  return nest([...entries, ...sections]);
}

/** A markdown file's headings to the third level, outside fences, each to the next heading of its level or above. */
export function outlineMarkdown(text) {
  const lines = text.split('\n');
  const inFence = fenced(lines);
  const heads = [];
  lines.forEach((line, i) => {
    const m = !inFence[i] && /^(#{1,3})\s+(.+?)\s*#*\s*$/.exec(line);
    if (m) heads.push({ start: i, level: m[1].length, name: truncate(m[2], 90) });
  });
  const top = Math.min(...heads.map((head) => head.level));
  return heads.map((head, k) => {
    const next = heads.slice(k + 1).find((other) => other.level <= head.level);
    let end = (next ? next.start : lines.length) - 1;
    while (end > head.start && !lines[end].trim()) end -= 1;
    return { start: head.start + 1, end: end + 1, depth: head.level - top, name: head.name };
  });
}

const CODE = /\.(cs|ts|tsx|mts|cts|mjs|cjs|js)$/;

/** The outline of one file by its kind, or null for a kind with none. */
function outlineOf(path, text) {
  if (path.endsWith('.cs')) return outlineCSharp(text);
  if (CODE.test(path)) return outlineScript(text, path);
  if (path.endsWith('.md')) return outlineMarkdown(text);
  return null;
}

// ---------------------------------------------------------------------------------------------------
// The files a session reads whole, and their outlines

/** `daoris.json` at `root`, or an empty manifest where there is none. */
function readManifest(root) {
  const manifest = join(root, 'daoris.json');
  return existsSync(manifest) ? JSON.parse(readFileSync(manifest, 'utf8')) ?? {} : {};
}

/** The path a role is declared at in the manifest's `documents`, `/`-separated, or null: a path, or `{ path }`. */
function declaredPath(manifest, role) {
  const entry = manifest.documents?.[role];
  const path = typeof entry === 'string' ? entry : entry?.path;
  return typeof path === 'string' ? path.replace(/\\/g, '/').replace(/\/+$/, '') : null;
}

/**
 * The records read by lookup, never whole, which get no outline: their headings are their entries, and a record is
 * searched for the identifier a row names (development-documents). The decisions have the digest instead.
 */
function lookupRecords(root) {
  const manifest = readManifest(root);
  const paths = ['decisions', 'archive', 'fixes', 'changelog', 'backlog'].map((role) => declaredPath(manifest, role)).filter(Boolean);
  return (path) => paths.some((record) => path === record || path.startsWith(`${record}/`)) || path.startsWith('docs/archive/');
}

function largeFiles(ctx) {
  const record = lookupRecords(ctx.root);
  return ctx.files
    .filter((path) => (CODE.test(path) || path.endsWith('.md')) && !record(path) && !/(^|\/)[^/]*fixtures\//.test(path))
    .map((path) => ({ path, bytes: Buffer.byteLength(ctx.read(path), 'utf8') }))
    .filter((file) => file.bytes > LARGE)
    .map((file) => ({ ...file, lines: ctx.read(file.path).split('\n').length - (ctx.read(file.path).endsWith('\n') ? 1 : 0) }));
}

function outlinePage(file, entries) {
  const kind = file.path.endsWith('.md') ? 'heading' : 'declaration';
  const out = [
    `# Outline of \`${file.path}\``,
    '',
    `${GENERATED} ${kb(file.bytes)} KB, ${file.lines} lines. Each row is a ${kind} and its lines: read it with offset = the first line and limit = the range's length.`,
    '',
  ];
  if (entries.length === 0) out.push(`No ${kind} was found.`);
  for (const entry of entries) out.push(`${'  '.repeat(entry.depth)}- ${entry.start}-${entry.end} ${entry.name}`);
  return `${out.join('\n')}\n`;
}

// ---------------------------------------------------------------------------------------------------
// Bridge routes

const DIRECT = /'(DAORIS\.[A-Z]+)'\s*,\s*'([A-Z][A-Z_]*)'/g;
const FORWARDED = /'(DAORIS\.[A-Z]+)'\s*,\s*([A-Za-z_$][\w$]*)\s*[,)]/g;
const ROUTE_LITERAL = /'([A-Z][A-Z_]*)'/g;
const NAME = /^[A-Za-z_$][\w$]*$/;

/**
 * The first argument of a call whose name ends at `at`: past its type arguments, to the first comma or close at depth
 * zero, with where it starts. Null when what follows is not a call. As `DriverModuleRoutesTests.FirstArgument` reads it.
 */
export function firstArgument(text, at) {
  if (text[at] === '<') {
    let depth = 0;
    for (; at < text.length; at += 1) {
      if (text[at] === '<') depth += 1;
      else if (text[at] === '>' && text[at - 1] !== '=' && --depth === 0) break;
    }
    at += 1;
  }
  while (at < text.length && /\s/.test(text[at])) at += 1;
  if (text[at] !== '(') return null;
  const start = at + 1;
  let nesting = 0;
  let quote = null;
  for (at = start; at < text.length; at += 1) {
    const c = text[at];
    if (quote) {
      if (c === quote && text[at - 1] !== '\\') quote = null;
    } else if (c === "'" || c === '"' || c === '`') quote = c;
    else if ('([{'.includes(c)) nesting += 1;
    else if (')]}'.includes(c) && nesting > 0) nesting -= 1;
    else if ((c === ',' || c === ')') && nesting === 0) return { text: text.slice(start, at), start };
  }
  return null;
}

/** A script's top-level names by line, so a call is named by the declaration it is written in. */
function topLevelNames(text) {
  return text.split('\n').flatMap((line, i) => {
    const m = /^(?:export\s+)?(?:default\s+)?(?:async\s+)?(?:function\s*\*?\s*|const\s+|let\s+|class\s+)([A-Za-z_$][\w$]*)/.exec(line);
    return m ? [{ line: i + 1, name: m[1] }] : [];
  });
}

/** Each call of one of `senders` in `text`: the sender, the call's first argument, and where that starts. */
function sends(text, senders) {
  if (senders.size === 0) return [];
  const caller = new RegExp(`(?<![.\\w$])(${[...senders.keys()].map((name) => name.replace(/\$/g, '\\$')).join('|')})\\s*(?=[<(])`, 'g');
  return [...text.matchAll(caller)].flatMap((m) => {
    const argument = firstArgument(text, m.index + m[0].length);
    return argument ? [{ sender: m[1], ...argument }] : [];
  });
}

/**
 * Every route the page sends a desktop module, from the bridge's files: module, route, file, line, and the function it
 * is written in. A send names its route in a direct `invoke('DAORIS.X', 'ROUTE')`, or as the first argument of a helper
 * that forwards its own route argument to one: `call` and `callBrowser`, and a helper of a helper (`useWiringChange`).
 * Helpers are found, never listed, so a new one cannot hide its callers' routes (the modules' route test keeps a list,
 * `DriverModuleRoutesTests.Forwarders`, for the driver's alone).
 */
function pageCalls(ctx) {
  const files = ctx.files.filter((path) => path.startsWith(BRIDGE) && /^[^/]+\.ts$/.test(path.slice(BRIDGE.length)) && !path.endsWith('.test.ts'));
  if (ctx.has(SHELL)) files.push(SHELL);
  const sources = files.map((file) => {
    const text = ctx.read(file);
    const tops = topLevelNames(text);
    return { file, text, from: (offset) => tops.filter((top) => top.line <= lineAt(text, offset)).at(-1)?.name ?? '' };
  });
  // A declaration that passes a name, not a literal, as the route is a helper of that module; found until none is new.
  const senders = new Map();
  for (let grew = true; grew;) {
    grew = false;
    const learn = (name, module) => {
      if (name && !senders.has(name)) {
        senders.set(name, module);
        grew = true;
      }
    };
    for (const { text, from } of sources) {
      for (const m of text.matchAll(FORWARDED)) learn(from(m.index), m[1]);
      for (const send of sends(text, senders)) if (NAME.test(send.text.trim())) learn(from(send.start), senders.get(send.sender));
    }
  }
  const calls = [];
  for (const { file, text, from } of sources) {
    for (const m of text.matchAll(DIRECT)) calls.push({ module: m[1], route: m[2], file, line: lineAt(text, m.index), from: from(m.index) });
    for (const send of sends(text, senders)) {
      for (const literal of send.text.matchAll(ROUTE_LITERAL)) {
        const at = send.start + literal.index;
        calls.push({ module: senders.get(send.sender), route: literal[1], file, line: lineAt(text, at), from: from(at) });
      }
    }
  }
  return calls;
}

/**
 * Every route a module answers: the driver module's `[DriverRoute]` marks, each with the method under it, and every
 * other module's `case "ROUTE":` or `"ROUTE" =>` arms, in the class that names its module.
 */
function moduleHandlers(ctx) {
  const handlers = [];
  for (const file of ctx.files.filter((path) => path.startsWith(MODULES) && /^[^/]+\.cs$/.test(path.slice(MODULES.length)))) {
    const lines = ctx.lines(file);
    if (/^DriverModule(\.[A-Za-z]+)?\.cs$/.test(file.slice(MODULES.length))) {
      lines.forEach((line, i) => {
        const mark = /\[DriverRoute\("([A-Z][A-Z_]*)"\)\]/.exec(line);
        if (!mark) return;
        let j = i + 1;
        while (j < lines.length && /^\s*\[/.test(lines[j])) j += 1;
        const member = csMember(lines[j] ?? '', { inType: true });
        handlers.push({ module: 'DAORIS.DRIVER', route: mark[1], file, line: j + 1, method: member?.name ?? '' });
      });
      continue;
    }
    const name = /ModuleName\s*=>\s*"(DAORIS\.[A-Z]+)"/.exec(ctx.read(file))?.[1];
    if (!name) continue;
    lines.forEach((line, i) => {
      const arm = /^\s*case\s+"[A-Z][A-Z_]*"\s*:/.exec(line) ?? /^\s*"[A-Z][A-Z_]*"(?:\s+or\s+"[A-Z][A-Z_]*")*\s*=>/.exec(line);
      if (!arm) return;
      for (const route of arm[0].matchAll(/"([A-Z][A-Z_]*)"/g)) handlers.push({ module: name, route: route[1], file, line: i + 1, method: '' });
    });
  }
  return handlers;
}

function routesPage(ctx) {
  const calls = pageCalls(ctx);
  const handlers = moduleHandlers(ctx);
  const out = [
    '# Bridge routes',
    '',
    `${GENERATED} Every route the page sends a desktop module, the handler that answers it (in \`${MODULES}\`) and the bridge function that sends it (in \`${WEB_SRC}\`). A route nobody answers, or that no bridge file sends, says \`—\`. The service's HTTP routes follow.`,
  ];
  const modules = [...new Set([...calls, ...handlers].map((entry) => entry.module))].sort(compare);
  for (const module of modules) {
    const routes = [...new Set([...calls, ...handlers].filter((entry) => entry.module === module).map((entry) => entry.route))].sort(compare);
    out.push('', `## ${module} (${routes.length})`, '', '| Route | Handler | Sent by |', '|---|---|---|');
    for (const route of routes) {
      const answered = handlers.filter((entry) => entry.module === module && entry.route === route)
        .map((entry) => `\`${entry.file.slice(MODULES.length)}:${entry.line}\`${entry.method ? ` ${entry.method}` : ''}`);
      const seen = new Set();
      const sent = calls.filter((entry) => entry.module === module && entry.route === route)
        .filter((entry) => !seen.has(`${entry.file}:${entry.from}`) && seen.add(`${entry.file}:${entry.from}`))
        .map((entry) => `\`${entry.file.slice(WEB_SRC.length)}:${entry.line}\`${entry.from ? ` ${entry.from}` : ''}`);
      out.push(`| \`${route}\` | ${answered.join('; ') || '—'} | ${sent.join(', ') || '—'} |`);
    }
  }
  if (modules.length === 0) out.push('', 'No bridge route was found.');
  if (ctx.has(HTTP_HOST)) {
    const routes = ctx.lines(HTTP_HOST).flatMap((line, i) => {
      const m = CS_ROUTE.exec(line);
      return m ? [{ method: m[1].toUpperCase(), path: m[2], line: i + 1 }] : [];
    }).sort((a, b) => compare(a.path, b.path) || compare(a.method, b.method));
    out.push('', `## The service's HTTP routes (${routes.length})`, '', `Mapped in \`${HTTP_HOST}\`.`, '', '| Route | Mapped at |', '|---|---|');
    for (const route of routes) out.push(`| ${route.method} ${route.path} | \`Program.cs:${route.line}\` |`);
  }
  return `${out.join('\n')}\n`;
}

// ---------------------------------------------------------------------------------------------------
// Terminal verbs

/** The line a C# type is declared on, in the driver's code, by its name. */
function findClass(ctx, name) {
  const declares = new RegExp(`^\\s*(?:(?:public|internal|static|sealed|abstract|partial|file)\\s+)*class\\s+${name}\\b`);
  for (const file of ctx.files.filter((path) => DRIVER_CODE.some((folder) => path.startsWith(folder)) && path.endsWith('.cs'))) {
    const at = ctx.lines(file).findIndex((line) => declares.test(line));
    if (at >= 0) return { file, line: at + 1 };
  }
  return null;
}

function cliVerbs(ctx) {
  if (!ctx.has(CLI_TABLE)) return [];
  const table = ctx.read(CLI_TABLE);
  const modules = new Map([...table.matchAll(/import \{ command as (\w+) \} from '\.\/cli\/([\w-]+)\.ts'/g)].map((m) => [m[1], `src/Daoris.Cli/src/cli/${m[2]}.ts`]));
  const order = /COMMANDS[^=]*=\s*\[([\s\S]*?)\];/.exec(table)?.[1].match(/\w+/g) ?? [];
  return order.filter((id) => modules.has(id) && ctx.has(modules.get(id))).map((id) => {
    const file = modules.get(id);
    const source = ctx.read(file);
    const at = source.split('\n').findIndex((line) => /^\s*name:\s*'/.test(line)) + 1;
    // `run: commandSync`, or `run: (args) => commandTool(args, …)`: the function the row hands its words to.
    const run = /\brun:\s*(?:(?:async\s*)?\([^)]*\)\s*=>\s*)?([A-Za-z_$][\w$]*)/.exec(source)?.[1];
    let handler = '';
    if (run) {
      const from = new RegExp(`import \\{[^}]*\\b${run}\\b[^}]*\\} from '\\.\\./([\\w-]+)\\.ts'`).exec(source)?.[1];
      const target = from ? `src/Daoris.Cli/src/${from}.ts` : file;
      const line = ctx.has(target) ? ctx.lines(target).findIndex((text) => new RegExp(`^export\\s+(?:async\\s+)?(?:function\\s+|const\\s+)${run}\\b`).test(text)) : -1;
      if (line >= 0) handler = `\`${target.slice('src/Daoris.Cli/src/'.length)}:${line + 1}\` ${run}`;
    }
    const usage = /usage:\s*\[\s*(['"])((?:\\.|(?!\1).)*)\1/.exec(source)?.[2] ?? '';
    return {
      verb: /name:\s*'([^']+)'/.exec(source)?.[1] ?? id,
      kind: /kind:\s*'([^']+)'/.exec(source)?.[1] ?? '',
      at: `\`${file.slice('src/Daoris.Cli/src/'.length)}:${at}\``,
      handler,
      says: truncate(usage.trim().replace(/^\S+\s*/, '').replace(/\s{2,}/g, ' '), 70),
    };
  });
}

/**
 * The sub-verbs `DriverCommand.Usage` names after each verb: a form's second word, and each word after a `|` of a
 * group. A form line stands at the usage's form indent, or continues a form with `|`; a description is deeper, and its
 * words are never read as verbs (`sync brings each repository…` describes `trees sync`).
 */
function driverSubVerbs(ctx, verbs) {
  const subs = new Map(verbs.map((verb) => [verb, []]));
  if (!ctx.has(DRIVER_COMMAND)) return subs;
  const usage = (/Usage\s*=\s*"""([\s\S]*?)"""/.exec(ctx.read(DRIVER_COMMAND))?.[1] ?? '').split('\n');
  const formIndent = Math.min(...usage.filter((line) => subs.has(line.trim().split(/\s+/)[0])).map(indentOf));
  let current = null;
  const add = (word) => {
    const clean = current && /^\[?([a-z][a-z-]*(?:\|[a-z][a-z-]*)*)\]?$/.exec(word)?.[1];
    if (clean) for (const part of clean.split('|')) if (!subs.get(current).includes(part)) subs.get(current).push(part);
  };
  for (const line of usage) {
    const trimmed = line.trim();
    const continues = trimmed.startsWith('|') && indentOf(line) > formIndent;
    if (!trimmed || (indentOf(line) !== formIndent && !continues)) continue;
    for (const form of continues ? [trimmed] : trimmed.split('·')) {
      const tokens = form.trim().split(/\s+/);
      if (!continues) {
        current = subs.has(tokens[0]) ? tokens[0] : null;
        if (tokens[1]) add(tokens[1]);
      }
      tokens.forEach((token, k) => {
        if (token === '|' && tokens[k + 1]) add(tokens[k + 1]);
        else if (/^\|[a-z]/.test(token)) add(token.slice(1));
      });
    }
  }
  return subs;
}

function driverVerbs(ctx) {
  if (!ctx.has(DRIVER_HOST)) return [];
  const lines = ctx.lines(DRIVER_HOST);
  const verbs = [];
  lines.forEach((line, i) => {
    const m = /^\s*if \(args is \[((?:"[a-z-]+",\s*)+)/.exec(line);
    if (!m) return;
    const words = [...m[1].matchAll(/"([a-z-]+)"/g)].map((word) => word[1]);
    const verb = words.join(' ');
    // The class the verb is handed to, by the call that runs it; a predicate such as `WorkCommand.Asks` is not one.
    let handler = null;
    for (let j = i; j < Math.min(lines.length, i + 30); j += 1) {
      if (j > i && /^\s*if \(args is \[/.test(lines[j])) break;
      const call = /\b(\w+(?:Console|Command))\.(Run\w*|Install)\(/.exec(lines[j]);
      if (call) {
        handler = call[1];
        break;
      }
    }
    const entry = verbs.find((known) => known.verb === verb) ?? (verbs.push({ verb, routed: i + 1, handlers: [], files: [] }), verbs.at(-1));
    const where = handler ? findClass(ctx, handler) : null;
    const cell = where ? `\`${where.file.slice(DESKTOP.length)}:${where.line}\` ${handler}` : `\`Program.cs:${i + 1}\` (inline)`;
    if (!entry.handlers.includes(cell)) entry.handlers.push(cell);
    // A console usually hands its words to the library's command of the same name, where the sub-verbs are read.
    const library = handler?.endsWith('Console') ? findClass(ctx, handler.replace(/Console$/, 'Command')) : null;
    for (const file of [where?.file, library?.file]) if (file && !entry.files.includes(file)) entry.files.push(file);
  });
  if (ctx.has(DRIVER_COMMAND)) {
    const at = ctx.lines(DRIVER_COMMAND).findIndex((line) => /args\[0\] == "drive"/.test(line));
    verbs.push({ verb: 'drive', routed: lines.findIndex((line) => /DriverCommand\.Read\(/.test(line)) + 1, handlers: [`\`${DRIVER_COMMAND.slice(DESKTOP.length)}:${at + 1}\` DriverCommand.Read`], files: [] });
  }
  const subs = driverSubVerbs(ctx, verbs.map((verb) => verb.verb.split(' ')[0]));
  for (const verb of verbs) {
    const words = verb.verb.includes(' ') ? [] : subs.get(verb.verb) ?? [];
    verb.subs = words.map((word) => {
      for (const file of [...verb.files, DRIVER_HOST]) {
        const at = ctx.lines(file).findIndex((line) => line.includes(`"${word}"`));
        if (at >= 0) return `${word} \`${file.slice(file.lastIndexOf('/') + 1)}:${at + 1}\``;
      }
      return word;
    });
  }
  return verbs;
}

function devkitVerbs(ctx) {
  if (!ctx.has(DEVKIT)) return [];
  const lines = ctx.lines(DEVKIT);
  return lines.flatMap((line, i) => {
    const m = /^\s*"([a-z][a-z-]*)"(?:\s+or\s+"[^"]+")*\s*=>\s*(\w+)\(/.exec(line);
    if (!m) return [];
    const at = lines.findIndex((other, k) => k !== i && csMember(other, { inType: false })?.name === m[2]);
    return [{ verb: m[1], at: i + 1, handler: at >= 0 ? `\`Program.cs:${at + 1}\` ${m[2]}` : m[2] }];
  });
}

function desktopVerbs(ctx) {
  if (!ctx.has(DESKTOP_TOOL)) return [];
  return ctx.lines(DESKTOP_TOOL).flatMap((line, i) => {
    const m = /^\s*case\s+'([a-z][a-z-]*)':/.exec(line);
    return m ? [{ verb: m[1], at: i + 1 }] : [];
  });
}

function npmScripts(ctx) {
  return PACKAGES.filter((file) => ctx.has(file)).map((file) => {
    const lines = ctx.lines(file);
    const scripts = JSON.parse(ctx.read(file)).scripts ?? {};
    const from = lines.findIndex((line) => /^\s*"scripts"\s*:/.test(line));
    return {
      file,
      scripts: Object.entries(scripts).map(([name, command]) => ({
        name,
        at: lines.findIndex((line, k) => k > from && line.trimStart().startsWith(`${JSON.stringify(name)}:`)) + 1,
        command: truncate(String(command), 70),
      })),
    };
  });
}

const cell = (text) => text.replace(/\|/g, '\\|');

function verbsPage(ctx) {
  const out = ['# Terminal verbs', '', `${GENERATED} Where each terminal verb is routed and handled, by program.`];
  const cli = cliVerbs(ctx);
  if (cli.length) {
    out.push('', '## `daoris` (the CLI)', '', 'Each verb is a module of `src/Daoris.Cli/src/cli/`, its row in `COMMANDS` (`src/Daoris.Cli/src/cli.ts`); paths below are under `src/Daoris.Cli/src/`.', '',
      '| Verb | Class | Row | Handler | Usage |', '|---|---|---|---|---|');
    for (const verb of cli) out.push(`| \`${verb.verb}\` | ${verb.kind} | ${verb.at} | ${verb.handler || '—'} | ${cell(verb.says)} |`);
  }
  const driver = driverVerbs(ctx);
  if (driver.length) {
    out.push('', '## `daoris-driver` (the driver\'s headless host)', '',
      `Routed in \`${DRIVER_HOST}\`, its usage \`DriverCommand.Usage\` in \`${DRIVER_COMMAND}\`; handlers below are under \`${DESKTOP}\`. A sub-verb names where its word first appears: the handler, the library's command it hands to, or \`Program.cs\`.`, '',
      '| Verb | Routed at | Handled in | Sub-verbs |', '|---|---|---|---|');
    for (const verb of driver) out.push(`| \`${verb.verb}\` | \`Program.cs:${verb.routed}\` | ${verb.handlers.join('; ')} | ${verb.subs.join(' · ') || '—'} |`);
  }
  const devkit = devkitVerbs(ctx);
  if (devkit.length) {
    out.push('', '## `daoris-devkit`', '', `Routed in \`${DEVKIT}\`.`, '', '| Verb | Routed at | Handler |', '|---|---|---|');
    for (const verb of devkit) out.push(`| \`${verb.verb}\` | \`Program.cs:${verb.at}\` | ${verb.handler} |`);
  }
  const desktop = desktopVerbs(ctx);
  if (desktop.length) {
    out.push('', '## `npm run desktop -- <verb>`', '', `Each a \`case\` in \`${DESKTOP_TOOL}\`: ${desktop.map((verb) => `\`${verb.verb}\` ${verb.at}`).join(' · ')}.`);
  }
  for (const { file, scripts } of npmScripts(ctx)) {
    out.push('', `## npm scripts in \`${file}\``, '', '| Script | Line | Runs |', '|---|---|---|');
    for (const script of scripts) out.push(`| \`${script.name}\` | ${script.at} | ${cell(`\`${script.command.replace(/`/g, "'")}\``)} |`);
  }
  return `${out.join('\n')}\n`;
}

// ---------------------------------------------------------------------------------------------------
// Catalogues

function cataloguesPage(ctx) {
  const out = [
    '# Catalogue areas',
    '',
    `${GENERATED} A key's home is the area named by its longest dotted prefix that has a file (\`${LOCALES}index.ts\`): area \`settings.rules\` is \`${LOCALES}en/settings.rules.json\` and its \`zh\` twin. Second segments with three keys or more are counted, most first.`,
    '',
    '| Area | Keys | Languages | Second segments (keys) |',
    '|---|---|---|---|',
  ];
  const areas = new Map();
  for (const path of ctx.files.filter((file) => file.startsWith(LOCALES) && /^[a-z]+\/[^/]+\.json$/.test(file.slice(LOCALES.length)))) {
    const [language, name] = path.slice(LOCALES.length).split('/');
    const area = name.slice(0, -'.json'.length);
    if (!areas.has(area)) areas.set(area, { languages: [], keys: null });
    const entry = areas.get(area);
    entry.languages.push(language);
    if (language === 'en' || entry.keys === null) entry.keys = Object.keys(JSON.parse(ctx.read(path)));
  }
  for (const area of [...areas.keys()].sort(compare)) {
    const { languages, keys } = areas.get(area);
    const counts = new Map();
    for (const key of keys) {
      const rest = key.startsWith(`${area}.`) ? key.slice(area.length + 1) : null;
      const segment = rest?.includes('.') ? rest.split('.')[0] : null;
      if (segment) counts.set(segment, (counts.get(segment) ?? 0) + 1);
    }
    const ranked = [...counts].filter(([, n]) => n >= 3).sort((a, b) => b[1] - a[1] || compare(a[0], b[0]));
    const shown = ranked.slice(0, 8).map(([segment, n]) => `\`${segment}\` ${n}`);
    if (ranked.length > 8) shown.push(`+${ranked.length - 8} more`);
    out.push(`| \`${area}\` | ${keys.length} | ${languages.sort(compare).join(', ')} | ${shown.join(', ')} |`);
  }
  if (ctx.has(GLOSSARY)) {
    const lines = ctx.lines(GLOSSARY);
    const sections = lines.flatMap((line, i) => {
      const m = /^ {2}"([^"]+)"\s*:/.exec(line);
      return m ? [{ name: m[1], start: i + 1 }] : [];
    });
    sections.forEach((section, k) => {
      section.end = (k + 1 < sections.length ? sections[k + 1].start : lines.length) - 1;
    });
    const kinds = lines.flatMap((line, i) => {
      const m = /^ {4}"([a-z][\w-]*)"\s*:\s*\{/.exec(line);
      const within = sections.find((section) => section.name === 'kinds');
      return m && within && i + 1 > within.start && i + 1 <= within.end ? [`\`${m[1]}\` ${i + 1}`] : [];
    });
    const terms = lines.flatMap((line, i) => {
      const m = /^\s*\{\s*"term"\s*:\s*"([^"]+)"/.exec(line);
      return m ? [`\`${m[1]}\` ${i + 1}`] : [];
    });
    out.push('', '## The glossary', '', `\`${GLOSSARY}\`, the names people and code use, by section: ${sections.map((section) => `\`${section.name}\` ${section.start}-${section.end}`).join(' · ')}.`);
    if (kinds.length) out.push('', `Kinds, by line: ${kinds.join(', ')}.`);
    if (terms.length) out.push('', `Terms, by line: ${terms.join(', ')}.`);
  }
  return `${out.join('\n')}\n`;
}

// ---------------------------------------------------------------------------------------------------
// Test fixtures, stand-ins and kits

const FIXTURE_NAME = /(Fixture|Harness|StandIn|Stub|Fake|Host|Scratch|World|Builder|Bridge)$/;
const SCRIPT_FIXTURES = [
  (path) => /^src\/Daoris\.Cli\/test\/_[^/]+\.ts$/.test(path),
  (path) => path.startsWith('src/Daoris.Web/src/test/') && CODE.test(path),
  (path) => /^src\/Daoris\.Web\/src\/(?:.+\/)?(?:fixtures|[A-Za-z]+Fixtures|storyIcons)\.tsx?$/.test(path),
  (path) => path.startsWith('src/Daoris.Web/.storybook/') && CODE.test(path),
  (path) => path === 'src/Daoris.Web/scripts/e2e-host.mjs',
  (path) => /^tools\/(?:[a-z-]+-kit|testbed)\.mjs$/.test(path),
];

/** The .NET suites' helpers: each helper file's types and their non-private members, and the shared types a test file declares. */
function dotnetFixtures(ctx) {
  const suites = new Map();
  for (const path of ctx.files.filter((file) => file.endsWith('.cs') && /\/[A-Za-z.]*Tests\//.test(file))) {
    const suite = /^(.*?[A-Za-z.]*Tests)\//.exec(path)[1];
    const base = path.slice(suite.length + 1);
    if (/(^|\/)(GlobalUsings|AssemblyInfo)\.cs$/.test(base) || base.includes('/obj/') || base.includes('/bin/')) continue;
    const entries = outlineCSharp(ctx.read(path));
    const own = base.split('/').pop().slice(0, -'.cs'.length);
    const helper = !base.endsWith('Tests.cs');
    const rows = [];
    for (const type of entries.filter((entry) => entry.kind === 'type')) {
      // A nested type is private unless it says otherwise; a top-level one is internal unless it says otherwise.
      const open = type.depth > 0 ? /\b(public|internal|protected)\b/.test(type.modifiers) : !/\bprivate\b/.test(type.modifiers);
      if (helper) {
        if (!open && type.depth > 0) continue;
        const members = entries.filter((entry) => entry.kind === 'member' && entry.start > type.start && entry.end <= type.end && entry.depth === type.depth + 1
          && /\b(public|internal|protected)\b/.test(entry.modifiers ?? '') && entry.member !== type.type);
        const names = [];
        for (const member of members) if (!names.some((name) => name.startsWith(`${member.member} `))) names.push(`${member.member} ${member.start}`);
        rows.push(`- \`${base}:${type.start}\` ${type.name}${names.length ? `: ${names.join(', ')}` : ''}`);
      } else if (type.type !== own && !/Tests$/.test(type.type) && (open || FIXTURE_NAME.test(type.type))) {
        rows.push(`- \`${base}:${type.start}\` ${type.name}${open ? '' : ' (private)'}`);
      }
    }
    if (!rows.length) continue;
    if (!suites.has(suite)) suites.set(suite, []);
    suites.get(suite).push(...rows);
  }
  return suites;
}

function fixturesPage(ctx) {
  const out = ['# Test fixtures, stand-ins and kits', '', `${GENERATED} By suite: each helper file's types and their non-private members, each test file's shared or stand-in types, and the scripts' fixtures and kits by export, each with its line.`];
  for (const [suite, rows] of [...dotnetFixtures(ctx)].sort((a, b) => compare(a[0], b[0]))) out.push('', `## \`${suite}/\``, '', ...rows);
  const scripts = ctx.files.filter((path) => SCRIPT_FIXTURES.some((matches) => matches(path)));
  const groups = new Map();
  for (const path of scripts) {
    const folder = path.slice(0, path.lastIndexOf('/') + 1);
    const exports = outlineScript(ctx.read(path), path).filter((entry) => entry.exported && entry.indent === 0);
    if (!groups.has(folder)) groups.set(folder, []);
    const names = [];
    for (const entry of exports) if (!names.some((name) => name.startsWith(`${entry.id} `))) names.push(`${entry.id} ${entry.start}`);
    groups.get(folder).push(`- \`${path.slice(folder.length)}\`: ${names.join(', ') || '(no export)'}`);
  }
  for (const folder of [...groups.keys()].sort(compare)) out.push('', `## \`${folder}\``, '', ...groups.get(folder));
  return `${out.join('\n')}\n`;
}

// ---------------------------------------------------------------------------------------------------
// The decisions digest (ORIENT1b)

/**
 * A note's label: the emphasised span that opens its line, when it is dated or in one of the forms the record writes
 * undated (`doc-duplicates`' `isNoteLabel`), cut to a row. Null for any other line.
 */
export function noteLabel(line) {
  let span = null;
  if (line.startsWith('**')) {
    const end = line.indexOf('**', 2);
    span = end > 0 ? line.slice(2, end) : line.slice(2);
  } else if (line.startsWith('*') && line[1] !== ' ') {
    let end = -1;
    for (let k = 1; k < line.length; k += 1) {
      if (line[k] !== '*') continue;
      if (line[k + 1] === '*' || line[k - 1] === '*') continue;
      end = k;
      break;
    }
    span = end > 0 ? line.slice(1, end) : line.slice(1);
  }
  if (span === null || !span.trim()) return null;
  if (!/\d{4}-\d{2}-\d{2}/.test(span) && !isNoteLabel(line)) return null;
  return truncate(span, 80);
}

/**
 * One decision file read for the digest: its title and date, its entry's lines before the first note, and each note's.
 * The service's `DecisionNotes` finds and labels the notes by the same rules with code of its own (ORIENT1g); both are
 * held to `orient-index-fixtures/decision-notes.json`, row for row, here by `orient-index.test.mjs` (ORIENT1h).
 */
function readDecision(id, lines) {
  const inFence = fenced(lines);
  const heading = lines.findIndex((line, i) => !inFence[i] && line.startsWith(`## ${id}`));
  const title = heading >= 0 ? lines[heading].slice(`## ${id}`.length).replace(/^\s*[—–-]\s*/, '') : '';
  const notes = [];
  // The entry's own first paragraph is never a note, even dated (`*Decided 2026-08-05.*`, `**Decision (DOC8, …)**`);
  // an entry whose title carries no date is dated there.
  const opening = lines.findIndex((line, i) => i > heading && line.trim() !== '');
  const date = /\((\d{4}-\d{2}-\d{2})\)\s*$/.exec(title)?.[1] ?? (opening >= 0 ? /\d{4}-\d{2}-\d{2}/.exec(lines[opening])?.[0] : null) ?? null;
  lines.forEach((line, i) => {
    if (i <= opening || inFence[i] || (i > 0 && lines[i - 1].trim() !== '')) return;
    const dated = /^###\s+(.+)$/.exec(line);
    const label = dated && /\d{4}-\d{2}-\d{2}/.test(dated[1]) ? truncate(dated[1], 80) : noteLabel(line);
    if (label) notes.push({ start: i, label });
  });
  // Each part runs to the line before the next, blank lines at its end left out.
  const until = (from, next) => {
    let end = next - 1;
    while (end > from && !lines[end].trim()) end -= 1;
    return end + 1;
  };
  notes.forEach((note, k) => {
    note.end = until(note.start, k + 1 < notes.length ? notes[k + 1].start : lines.length);
  });
  return {
    id,
    start: heading + 1,
    end: until(Math.max(heading, 0), notes.length ? notes[0].start : lines.length),
    date,
    title: title.replace(/\s*\(\d{4}-\d{2}-\d{2}\)\s*$/, ''),
    notes,
  };
}

/**
 * The digest (ORIENT1b): every decision's title with its entry's own lines, then every dated note with its lines, so a
 * session reads the decision or the one note it needs and not the file. Titles first, so they read in one go.
 */
function decisionsPage(ctx) {
  const folder = declaredDecisions(ctx.root);
  const decisions = ctx.files.filter((path) => path.startsWith(`${folder}/`) && /^D[1-9]\d*\.md$/.test(path.slice(folder.length + 1)))
    .map((path) => path.slice(folder.length + 1)).sort(byNumber)
    .map((name) => readDecision(name.slice(0, -'.md'.length), ctx.lines(`${folder}/${name}`)));
  const titles = decisions.map((decision) => {
    const notes = decision.notes.length ? ` · ${decision.notes.length} note${decision.notes.length === 1 ? '' : 's'}` : '';
    return `- ${decision.id}:${decision.start}-${decision.end}${decision.date ? ` (${decision.date})` : ''} ${truncate(decision.title, 90)}${notes}`;
  });
  const notes = decisions.flatMap((decision) => decision.notes.map((note) => `- ${decision.id}:${note.start + 1}-${note.end} ${note.label}`));
  const head = [
    '# Decisions digest',
    '',
    '', // the sentence below, once the line numbers are known
    '',
    `## Decisions (${decisions.length})`,
    '',
  ];
  const titlesAt = head.length + 1;
  const notesAt = titlesAt + titles.length + 3;
  head[2] = `${GENERATED} \`D<n>:<a>-<b>\` is lines a to b of \`${folder}/D<n>.md\`: read them with offset a and limit b - a + 1. First each decision's title, with the lines of its entry before its notes (here lines ${titlesAt}-${titlesAt + titles.length - 1}); then each dated note, with its lines (from line ${notesAt}). Search for \`D<n>:\` to list one decision's rows.`;
  const out = [...head, ...titles, '', `## Notes (${notes.length})`, '', ...notes];
  if (decisions.length === 0) out.push(`No decision file was found in \`${folder}/\`.`);
  return `${out.join('\n')}\n`;
}

// ---------------------------------------------------------------------------------------------------
// The index's own page

/** The code map (MAP3c): the projects, each with its path, written and checked by the devkit's `map`. */
const CODE_MAP = 'docs/code-map.json';

/**
 * The indexes kept elsewhere, each named only when the tree holds it (ORIENT2a2, the canon's `templates/index.md`).
 * `byHand` are the README's *Kept by hand* rows, listed before the generated files because nothing below restates
 * theirs: the router, then the lanes map, whose lanes group the large files below. `generated` are the indexes
 * another tool writes, named in the opening as the template names the knowledge's: the doctrine's `INDEX.md` and
 * the code map.
 */
function keptElsewhere(ctx) {
  const manifest = readManifest(ctx.root);
  const router = declaredPath(manifest, 'router');
  const byHand = [
    router && ctx.has(router) && [router, 'every document, its kind, what it is for and where it stands'],
    ctx.has(LANES_FILE) && [LANES_FILE, `each lane's id, title and summary, and the paths it owns: which part of the code a path is in, and how the files over ${LARGE / 1024} KB below are grouped`],
  ].filter(Boolean);
  const knowledge = `${(typeof manifest.target === 'string' ? manifest.target : '.claude').replace(/\\/g, '/').replace(/\/+$/, '')}/INDEX.md`;
  const generated = [
    ctx.has(knowledge) && `the knowledge and the skills in \`${knowledge}\`, written by \`daoris sync\``,
    ctx.has(CODE_MAP) && `the projects in \`${CODE_MAP}\`, written by the devkit's \`map\``,
  ].filter(Boolean);
  return { byHand, generated };
}

function readmePage(ctx, large) {
  const { byHand, generated } = keptElsewhere(ctx);
  const out = [
    '# The orientation index',
    '',
    `${GENERATED} Read here before searching: each row names a file and line to open, and a range to read with offset and limit. \`--check\` fails when the index is stale and runs at every merge, and the merge tool writes the index into each merge.`,
  ];
  if (generated.length) {
    out.push('', `Listed elsewhere, by tools of their own: ${generated.join('; ')}. Open those for what they list: nothing here restates ${generated.length === 1 ? 'it' : 'them'}.`);
  }
  out.push('', '## Kept by hand', '');
  if (byHand.length) {
    out.push(
      'Listed first, because nothing below restates their rows: open one of these for what it answers.',
      '',
      '| Index | Answers |',
      '|---|---|',
      ...byHand.map(([path, answers]) => `| \`${path}\` | ${answers} |`),
    );
  } else {
    out.push('None: this tree keeps no index by hand.');
  }
  out.push(
    '',
    '## Generated',
    '',
    '| File | Answers |',
    '|---|---|',
    '| `routes.md` | which module answers a bridge route, and which bridge function sends it; the service\'s HTTP routes |',
    '| `verbs.md` | where each terminal verb is routed and handled: `daoris`, `daoris-driver`, the devkit, `npm run desktop`, the npm scripts |',
    '| `catalogues.md` | which catalogue file holds a key, by area; the glossary\'s sections, kinds and terms by line |',
    '| `fixtures.md` | the test fixtures, stand-ins and kits by name, with file and line |',
    '| `decisions.md` | each decision\'s title with its entry\'s lines, then each dated note with its lines |',
    `| \`outlines/<path>.md\` | the declarations or headings of a file over ${LARGE / 1024} KB, each with its line range |`,
    '',
    `## Files over ${LARGE / 1024} KB (${large.length})`,
    '',
    'Each has its outline at `outlines/<its path>.md`: open the outline, then read the range you need, not the file.',
  );
  let lanes = null;
  try {
    lanes = readLanes(ctx.root)?.lanes ?? null;
  } catch {
    lanes = null;
  }
  const groups = new Map();
  for (const file of large) {
    const steward = lanes?.find((lane) => lane.steward && laneMatcher(lane.paths)(file.path));
    const lane = steward ?? lanes?.find((candidate) => laneMatcher(candidate.paths)(file.path));
    const name = lane ? `${lane.title} (\`${lane.id}\`)` : lanes ? 'No lane' : 'Files';
    if (!groups.has(name)) groups.set(name, []);
    groups.get(name).push(file);
  }
  const order = [...(lanes ?? []).map((lane) => `${lane.title} (\`${lane.id}\`)`), 'No lane', 'Files'];
  for (const name of order.filter((group) => groups.has(group))) {
    out.push('', `### ${name}`, '', '| File | KB | Lines |', '|---|---|---|');
    for (const file of groups.get(name)) out.push(`| \`${file.path}\` | ${kb(file.bytes)} | ${file.lines} |`);
  }
  return `${out.join('\n')}\n`;
}

// ---------------------------------------------------------------------------------------------------
// Plan, check, apply

/** The index the tree at `root` says, as `docs/index/…` path to content. Writes nothing. */
export function planIndex(root, files = listFiles(root)) {
  const ctx = reader(root, files.filter((path) => !path.startsWith(`${INDEX}/`)));
  const large = largeFiles(ctx);
  const planned = new Map([
    [`${INDEX}/README.md`, readmePage(ctx, large)],
    [`${INDEX}/routes.md`, routesPage(ctx)],
    [`${INDEX}/verbs.md`, verbsPage(ctx)],
    [`${INDEX}/catalogues.md`, cataloguesPage(ctx)],
    [`${INDEX}/fixtures.md`, fixturesPage(ctx)],
    [`${INDEX}/decisions.md`, decisionsPage(ctx)],
  ]);
  for (const file of large) planned.set(`${INDEX}/outlines/${file.path}.md`, outlinePage(file, outlineOf(file.path, ctx.read(file.path)) ?? []));
  return planned;
}

function filesUnder(root, at) {
  const folder = join(root, at);
  if (!existsSync(folder)) return [];
  return readdirSync(folder, { withFileTypes: true }).flatMap((entry) => {
    const path = `${at}/${entry.name}`;
    return entry.isDirectory() ? filesUnder(root, path) : [path];
  });
}

/** Where `docs/index/` differs from the plan: a file missing, stale, or not one the tool generates. */
export function staleness(root, planned) {
  const found = [];
  for (const [path, content] of planned) {
    const file = join(root, path);
    if (!existsSync(file)) found.push({ path, fact: 'missing' });
    else if (readFileSync(file, 'utf8') !== content) found.push({ path, fact: 'stale' });
  }
  for (const path of filesUnder(root, INDEX)) if (!planned.has(path)) found.push({ path, fact: 'not generated' });
  return found.sort((a, b) => compare(a.path, b.path));
}

function removeEmpty(folder) {
  if (!existsSync(folder)) return;
  for (const entry of readdirSync(folder, { withFileTypes: true })) if (entry.isDirectory()) removeEmpty(join(folder, entry.name));
  if (readdirSync(folder).length === 0) rmdirSync(folder);
}

/** Writes what the plan changes, each file beside and renamed, and removes what it does not generate. */
export function applyIndex(root, planned) {
  const changed = staleness(root, planned);
  for (const { path, fact } of changed) {
    const file = join(root, path);
    if (fact === 'not generated') {
      rmSync(file, { force: true });
      continue;
    }
    writeAtomic(file, planned.get(path));
  }
  removeEmpty(join(root, INDEX));
  return changed;
}

if (isMain(import.meta.url)) {
  const args = process.argv.slice(2);
  const rootAt = args.indexOf('--root');
  const unknown = args.filter((arg, i) => arg !== '--check' && arg !== '--root' && !(rootAt >= 0 && i === rootAt + 1));
  if (unknown.length || (rootAt >= 0 && !args[rootAt + 1])) {
    console.error('usage: node tools/orient-index.mjs [--check] [--root <dir>]');
    process.exit(2);
  }
  const root = rootAt >= 0 ? resolve(args[rootAt + 1]) : join(dirname(fileURLToPath(import.meta.url)), '..');
  let planned;
  try {
    planned = planIndex(root);
  } catch (error) {
    console.error(`orient-index: ${error.message}`);
    process.exit(2);
  }
  if (args.includes('--check')) {
    const stale = staleness(root, planned);
    if (stale.length) {
      console.error(`orient-index: ${INDEX}/ is stale in ${stale.length} file(s); node tools/orient-index.mjs writes it again:`);
      for (const { path, fact } of stale) console.error(`  ${path}: ${fact}`);
      process.exit(1);
    }
    console.log(`orient-index: ${INDEX}/ is fresh, ${planned.size} files`);
  } else {
    const changed = applyIndex(root, planned);
    console.log(`orient-index: ${INDEX}/ written, ${changed.length} of ${planned.size} files changed`);
  }
}
