import { join } from 'node:path';
import { listMarkdown, readText, writeTextAtomic } from './fsx.mjs';
import { parseFrontmatter, stripHeader, SKILL_FIELDS } from './document.mjs';
import { lockIndex, readLock, readManifest } from './config.mjs';

export const INDEX_PATH = 'rules/RULES_INDEX.md';
const INDEX_FILE = 'RULES_INDEX.md';
const TABLE_HEAD = '| Rule | Applies when | Enforces |\n|---|---|---|';
const SKILL_TABLE_HEAD = '| Skill | Use when |\n|---|---|';

function rows(root, target, tier, locked) {
  const lines = [];
  for (const file of listMarkdown(join(root, target, tier))) {
    if (tier === 'rules' && file === INDEX_FILE) continue;
    const { meta } = parseFrontmatter(stripHeader(readText(join(root, target, tier, file))));
    const link = `[${file.replace(/\.md$/, '')}](${tier === 'rules' ? '' : `../${tier}/`}${file})`;
    const mark = locked.has(`${tier}/${file}`) ? '' : ' _(local)_';
    lines.push(
      meta
        ? `| ${link}${mark} | ${meta.applies_when} | ${meta.enforces} |`
        : `| ${link}${mark} | ⚠ needs frontmatter | ⚠ needs frontmatter |`,
    );
  }
  return lines;
}

/**
 * A skill is a directory, so the directory is its name and `SKILL.md` is an
 * implementation detail the roster should never show. This table is what makes
 * a hand-written "here are our skills" skill unnecessary: its content was always
 * generated (D14), and only a generated roster can be right in a repo whose
 * skill set the canon has never seen.
 */
function skillRows(root, target, locked) {
  const lines = [];
  for (const file of listMarkdown(join(root, target, 'skills'))) {
    if (!file.endsWith('/SKILL.md')) continue;
    const name = file.slice(0, -'/SKILL.md'.length);
    const text = stripHeader(readText(join(root, target, 'skills', file)));
    const { meta } = parseFrontmatter(text, SKILL_FIELDS);
    const mark = locked.has(`skills/${file}`) ? '' : ' _(local)_';
    lines.push(
      `| [${name}](../skills/${file})${mark} | ${meta ? meta.description : '⚠ needs frontmatter'} |`,
    );
  }
  return lines;
}

/**
 * Generated from what is actually on disk, so the index can never point at a
 * file that is not there. A file without frontmatter is marked, never dropped —
 * an index that looks complete while omitting a rule is the failure to avoid.
 */
export function buildIndex({ root, target, lock }) {
  const locked = lockIndex(lock);
  return [
    '# RULES_INDEX — generated by daoris; do not hand-edit',
    '',
    "Rows marked _(local)_ are this repo's own and are never synced.",
    '',
    '## Core (always loaded)',
    '',
    TABLE_HEAD,
    ...rows(root, target, 'rules', locked),
    '',
    '## Knowledge (read on demand)',
    '',
    TABLE_HEAD,
    ...rows(root, target, 'knowledge', locked),
    '',
    '## Skills (invoke by name)',
    '',
    SKILL_TABLE_HEAD,
    ...skillRows(root, target, locked),
    '',
  ].join('\n');
}

export function writeIndex(root, target, text) {
  writeTextAtomic(join(root, target, INDEX_PATH), text);
}

export function commandIndex({ root, write }) {
  const manifest = readManifest(root);
  const text = buildIndex({ root, target: manifest.target, lock: readLock(root) });
  writeIndex(root, manifest.target, text);
  write(`daoris: wrote ${manifest.target}/${INDEX_PATH}`);
  return 0;
}
