import { join } from 'node:path';
import { listMarkdown, readText, writeTextAtomic } from './fsx.mjs';
import { parseFrontmatter, stripHeader } from './document.mjs';
import { lockIndex, readLock, readManifest } from './config.mjs';

export const INDEX_PATH = 'rules/RULES_INDEX.md';
const INDEX_FILE = 'RULES_INDEX.md';
const TABLE_HEAD = '| Rule | Applies when | Enforces |\n|---|---|---|';

function rows(root, target, tier, locked) {
  const lines = [];
  for (const file of listMarkdown(join(root, target, tier))) {
    if (tier === 'rules' && file === INDEX_FILE) continue;
    const { meta } = parseFrontmatter(stripHeader(readText(join(root, target, tier, file))));
    const link = `[${file.replace(/\.md$/, '')}](${tier === 'rules' ? '' : `../${tier}/`}${file})`;
    const mark = locked.has(`${tier}/${file}`) ? '' : ' _(local)_';
    lines.push(
      meta
        ? `| ${link}${mark} | ${meta.applies_when} | ${meta.enforces} |`
        : `| ${link}${mark} | ⚠ needs frontmatter | ⚠ needs frontmatter |`,
    );
  }
  return lines;
}

/**
 * Generated from what is actually on disk, so the index can never point at a
 * file that is not there. A file without frontmatter is marked, never dropped —
 * an index that looks complete while omitting a rule is the failure to avoid.
 */
export function buildIndex({ root, target, lock }) {
  const locked = lockIndex(lock);
  return [
    '# RULES_INDEX — generated by daoris; do not hand-edit',
    '',
    "Rows marked _(local)_ are this repo's own and are never synced.",
    '',
    '## Core (always loaded)',
    '',
    TABLE_HEAD,
    ...rows(root, target, 'rules', locked),
    '',
    '## Knowledge (read on demand)',
    '',
    TABLE_HEAD,
    ...rows(root, target, 'knowledge', locked),
    '',
  ].join('\n');
}

export function writeIndex(root, target, text) {
  writeTextAtomic(join(root, target, INDEX_PATH), text);
}

export function commandIndex({ root, write }) {
  const manifest = readManifest(root);
  const text = buildIndex({ root, target: manifest.target, lock: readLock(root) });
  writeIndex(root, manifest.target, text);
  write(`daoris: wrote ${manifest.target}/${INDEX_PATH}`);
  return 0;
}
